//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class BottomMenu_X2pro7 : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock1;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button7;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button6;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private bool m_Initialized_BottomMenu_X2pro7;
        
        public BottomMenu_X2pro7() {
            this.InitializeComponent();
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_DigitalClock1 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_DigitalClock2 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_Button8 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button7 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button6 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            this.SuspendLayout();
            // 
            // BottomMenu_X2pro7
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_DigitalClock1
            // 
            this.m_DigitalClock1.BlinkDynamicsValue = false;
            this.m_DigitalClock1.DelayMouseInputPeriod = 0;
            this.m_DigitalClock1.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Date;
            this.m_DigitalClock1.EnabledDynamicsValue = true;
            this.m_DigitalClock1.FontSizePixels = 14;
            this.m_DigitalClock1.Height = 19;
            this.m_DigitalClock1.Left = 18;
            this.m_DigitalClock1.Name = "m_DigitalClock1";
            this.m_DigitalClock1.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_DigitalClock1.ShowDayOfWeek = false;
            this.m_DigitalClock1.ShowSeconds = true;
            this.m_DigitalClock1.Text = "4/29/2021";
            this.m_DigitalClock1.Top = 5;
            this.m_DigitalClock1.VisibleDynamicsValue = true;
            this.m_DigitalClock1.Width = 86;
            // 
            // m_DigitalClock2
            // 
            this.m_DigitalClock2.BlinkDynamicsValue = false;
            this.m_DigitalClock2.DelayMouseInputPeriod = 0;
            this.m_DigitalClock2.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Time;
            this.m_DigitalClock2.EnabledDynamicsValue = true;
            this.m_DigitalClock2.FontSizePixels = 14;
            this.m_DigitalClock2.Height = 19;
            this.m_DigitalClock2.Left = 20;
            this.m_DigitalClock2.Name = "m_DigitalClock2";
            this.m_DigitalClock2.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_DigitalClock2.ShowDayOfWeek = false;
            this.m_DigitalClock2.ShowSeconds = true;
            this.m_DigitalClock2.Text = "3:51:49 PM";
            this.m_DigitalClock2.Top = 20;
            this.m_DigitalClock2.VisibleDynamicsValue = true;
            this.m_DigitalClock2.Width = 93;
            // 
            // m_Button8
            // 
            this.m_Button8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BlinkDynamicsValue = false;
            this.m_Button8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button8.DelayMouseInputPeriod = 0;
            this.m_Button8.EnabledDynamicsValue = true;
            this.m_Button8.FontSizePixels = 14;
            this.m_Button8.ForceTransparency = true;
            this.m_Button8.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button8.Height = 42;
            this.m_Button8.IndicatorMargin = null;
            this.m_Button8.Left = 208;
            this.m_Button8.Name = "m_Button8";
            this.m_Button8.RequiresTransparency = true;
            this.m_Button8.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button8.StyleName = "Glossy";
            this.m_Button8.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button8.TextValue = 0D;
            this.m_Button8.TextWidth = 88;
            this.m_Button8.Top = 431;
            this.m_Button8.Value = 0D;
            this.m_Button8.VisibleDynamicsValue = true;
            this.m_Button8.VisualPropertiesHashCode = -550825218;
            this.m_Button8.Width = 94;
            // 
            // m_Button7
            // 
            this.m_Button7.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BlinkDynamicsValue = false;
            this.m_Button7.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button7.DelayMouseInputPeriod = 0;
            this.m_Button7.EnabledDynamicsValue = true;
            this.m_Button7.FontSizePixels = 14;
            this.m_Button7.ForceTransparency = true;
            this.m_Button7.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button7.Height = 42;
            this.m_Button7.IndicatorMargin = null;
            this.m_Button7.Left = 688;
            this.m_Button7.Name = "m_Button7";
            this.m_Button7.RequiresTransparency = true;
            this.m_Button7.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button7.StyleName = "Glossy";
            this.m_Button7.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button7.TextValue = 0D;
            this.m_Button7.TextWidth = 88;
            this.m_Button7.Top = 431;
            this.m_Button7.Value = 0D;
            this.m_Button7.VisibleDynamicsValue = true;
            this.m_Button7.VisualPropertiesHashCode = 457959621;
            this.m_Button7.Width = 94;
            // 
            // m_Button6
            // 
            this.m_Button6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BlinkDynamicsValue = false;
            this.m_Button6.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button6.DelayMouseInputPeriod = 0;
            this.m_Button6.EnabledDynamicsValue = true;
            this.m_Button6.FontSizePixels = 14;
            this.m_Button6.ForceTransparency = true;
            this.m_Button6.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button6.Height = 42;
            this.m_Button6.IndicatorMargin = null;
            this.m_Button6.Left = 592;
            this.m_Button6.Name = "m_Button6";
            this.m_Button6.RequiresTransparency = true;
            this.m_Button6.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button6.StyleName = "Glossy";
            this.m_Button6.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button6.TextValue = 0D;
            this.m_Button6.TextWidth = 88;
            this.m_Button6.Top = 431;
            this.m_Button6.Value = 0D;
            this.m_Button6.VisibleDynamicsValue = true;
            this.m_Button6.VisualPropertiesHashCode = -550825218;
            this.m_Button6.Width = 94;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button5.DelayMouseInputPeriod = 0;
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontSizePixels = 14;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button5.Height = 42;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 496;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button5.StyleName = "Glossy";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 88;
            this.m_Button5.Top = 431;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = -550825218;
            this.m_Button5.Width = 94;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button4.DelayMouseInputPeriod = 0;
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontSizePixels = 14;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button4.Height = 42;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 400;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button4.StyleName = "Glossy";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 88;
            this.m_Button4.Top = 431;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = -550825218;
            this.m_Button4.Width = 94;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button3.DelayMouseInputPeriod = 0;
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontSizePixels = 14;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button3.Height = 42;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 304;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button3.StyleName = "Glossy";
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 88;
            this.m_Button3.Top = 431;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = -550825218;
            this.m_Button3.Width = 94;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button2.DelayMouseInputPeriod = 0;
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontSizePixels = 14;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button2.Height = 42;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 112;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button2.StyleName = "Glossy";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 88;
            this.m_Button2.Top = 431;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = -550825218;
            this.m_Button2.Width = 94;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 14;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button1.Height = 42;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 16;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Button1.StyleName = "Glossy";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 88;
            this.m_Button1.Top = 431;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -1997125935;
            this.m_Button1.Width = 94;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.DelayMouseInputPeriod = 0;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(224)))), ((int)(((byte)(236))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 384;
            this.m_Rectangle1.Left = 15;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Top = 43;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 768;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 29;
            this.m_Picture.Left = 702;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "BottomMenu_X2pro7";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "beijer-electronics1";
            this.m_Picture.Top = 7;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 72;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "BottomMenu_X2pro7";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_BottomMenu_X2pro7 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_BottomMenu_X2pro7) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_DigitalClock1);
            this.DrawingPrimitives.Add(this.m_DigitalClock2);
            this.DrawingPrimitives.Add(this.m_Button8);
            this.DrawingPrimitives.Add(this.m_Button7);
            this.DrawingPrimitives.Add(this.m_Button6);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Picture);
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(BottomMenu_X2pro7));
            this.m_Button8.Text = resources.GetText("BottomMenu_X2pro7.Button8.Text", "Screen 3");
            this.m_Button7.Text = resources.GetText("BottomMenu_X2pro7.Button7.Text", "Screen 8");
            this.m_Button6.Text = resources.GetText("BottomMenu_X2pro7.Button6.Text", "Screen 7");
            this.m_Button5.Text = resources.GetText("BottomMenu_X2pro7.Button5.Text", "Screen 6");
            this.m_Button4.Text = resources.GetText("BottomMenu_X2pro7.Button4.Text", "Screen 5");
            this.m_Button3.Text = resources.GetText("BottomMenu_X2pro7.Button3.Text", "Screen 4");
            this.m_Button2.Text = resources.GetText("BottomMenu_X2pro7.Button2.Text", "Screen 2");
            this.m_Button1.Text = resources.GetText("BottomMenu_X2pro7.Button1.Text", "Screen 1");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_BottomMenu_X2pro7) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
