//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class DiagnosticsScreen : MainScreen, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text7;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox4;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox5;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text9;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button6;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox1;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox2;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group1;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox7;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox8;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox9;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox10;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox11;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox12;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolViewbox13;
        
        private bool m_Initialized_DiagnosticsScreen;
        
        public DiagnosticsScreen() {
            this.InitializeComponent();
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button5.Click += new System.EventHandler(this.m_Button5_Action_Click);
            this.m_Button6.Click += new System.EventHandler(this.m_Button6_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_Button2.Click += new System.EventHandler(this.m_Button2_Action_Click);
            this.m_Button3.Click += new System.EventHandler(this.m_Button3_Action_Click);
            this.m_Button4.Click += new System.EventHandler(this.m_Button4_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolViewbox13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolViewbox13);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text7 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_SymbolViewbox4 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox5 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox6 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text9 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button6 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_SymbolViewbox1 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox2 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox3 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Group1 = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_SymbolViewbox7 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox8 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox9 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox10 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox11 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox12 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolViewbox13 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).BeginInit();
            this.SuspendLayout();
            // 
            // DiagnosticsScreen
            // 
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.DelayMouseInputPeriod = 0;
            this.m_Rectangle2.Enabled = false;
            this.m_Rectangle2.EnabledDynamicsValue = false;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(43)))), ((int)(((byte)(43))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 352;
            this.m_Rectangle2.Left = 432;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle2.Top = 112;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 352;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "Segoe UI";
            this.m_Text.FontSizePixels = 24;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text.Height = 21;
            this.m_Text.Left = 72;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(6D, 0D, 6D, 1D);
            this.m_Text.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 66;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 62;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "Arial";
            this.m_Button.FontSizePixels = 20;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button.Height = 40;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 702;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Button.StyleName = "Vintage";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 24;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 34;
            this.m_Button.Top = 176;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = 1250273231;
            this.m_Button.Width = 40;
            // 
            // m_Text6
            // 
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.DelayMouseInputPeriod = 0;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontFamily = "Segoe UI Semibold";
            this.m_Text6.FontSizePixels = 20;
            this.m_Text6.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text6.Height = 21;
            this.m_Text6.Left = 456;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text6.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text6.TextVerticalAlignment = "Center";
            this.m_Text6.Top = 130;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 65;
            // 
            // m_Text7
            // 
            this.m_Text7.BlinkDynamicsValue = false;
            this.m_Text7.Bold = true;
            this.m_Text7.DelayMouseInputPeriod = 0;
            this.m_Text7.EnabledDynamicsValue = true;
            this.m_Text7.FontFamily = "Segoe UI";
            this.m_Text7.FontSizePixels = 16;
            this.m_Text7.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text7.Height = 21;
            this.m_Text7.Left = 505;
            this.m_Text7.Name = "m_Text7";
            this.m_Text7.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text7.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text7.TextVerticalAlignment = "Center";
            this.m_Text7.Top = 184;
            this.m_Text7.VisibleDynamicsValue = true;
            this.m_Text7.Width = 91;
            // 
            // m_SymbolViewbox4
            // 
            this.m_SymbolViewbox4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox4.BlinkDynamicsValue = false;
            this.m_SymbolViewbox4.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox4.EnabledDynamicsValue = true;
            this.m_SymbolViewbox4.ForceTransparency = false;
            this.m_SymbolViewbox4.Height = 32;
            this.m_SymbolViewbox4.IndicatorMargin = null;
            this.m_SymbolViewbox4.Left = 456;
            this.m_SymbolViewbox4.Name = "m_SymbolViewbox4";
            this.m_SymbolViewbox4.RequiresTransparency = false;
            this.m_SymbolViewbox4.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox4.Top = 184;
            this.m_SymbolViewbox4.Value = 0D;
            this.m_SymbolViewbox4.VisibleDynamicsValue = true;
            this.m_SymbolViewbox4.Width = 40;
            // 
            // m_SymbolViewbox5
            // 
            this.m_SymbolViewbox5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox5.BlinkDynamicsValue = false;
            this.m_SymbolViewbox5.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox5.EnabledDynamicsValue = true;
            this.m_SymbolViewbox5.ForceTransparency = false;
            this.m_SymbolViewbox5.Height = 32;
            this.m_SymbolViewbox5.IndicatorMargin = null;
            this.m_SymbolViewbox5.Left = 456;
            this.m_SymbolViewbox5.Name = "m_SymbolViewbox5";
            this.m_SymbolViewbox5.RequiresTransparency = false;
            this.m_SymbolViewbox5.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox5.Top = 256;
            this.m_SymbolViewbox5.Value = 0D;
            this.m_SymbolViewbox5.VisibleDynamicsValue = true;
            this.m_SymbolViewbox5.Width = 40;
            // 
            // m_SymbolViewbox6
            // 
            this.m_SymbolViewbox6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox6.BlinkDynamicsValue = false;
            this.m_SymbolViewbox6.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox6.EnabledDynamicsValue = true;
            this.m_SymbolViewbox6.ForceTransparency = false;
            this.m_SymbolViewbox6.Height = 32;
            this.m_SymbolViewbox6.IndicatorMargin = null;
            this.m_SymbolViewbox6.Left = 456;
            this.m_SymbolViewbox6.Name = "m_SymbolViewbox6";
            this.m_SymbolViewbox6.RequiresTransparency = false;
            this.m_SymbolViewbox6.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox6.Top = 328;
            this.m_SymbolViewbox6.Value = 0D;
            this.m_SymbolViewbox6.VisibleDynamicsValue = true;
            this.m_SymbolViewbox6.Width = 40;
            // 
            // m_Text8
            // 
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.Bold = true;
            this.m_Text8.DelayMouseInputPeriod = 0;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontFamily = "Segoe UI";
            this.m_Text8.FontSizePixels = 16;
            this.m_Text8.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text8.Height = 21;
            this.m_Text8.Left = 505;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text8.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text8.TextVerticalAlignment = "Center";
            this.m_Text8.Top = 256;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 91;
            // 
            // m_Text9
            // 
            this.m_Text9.BlinkDynamicsValue = false;
            this.m_Text9.Bold = true;
            this.m_Text9.DelayMouseInputPeriod = 0;
            this.m_Text9.EnabledDynamicsValue = true;
            this.m_Text9.FontFamily = "Segoe UI";
            this.m_Text9.FontSizePixels = 16;
            this.m_Text9.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text9.Height = 21;
            this.m_Text9.Left = 505;
            this.m_Text9.Name = "m_Text9";
            this.m_Text9.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text9.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text9.TextVerticalAlignment = "Center";
            this.m_Text9.Top = 328;
            this.m_Text9.VisibleDynamicsValue = true;
            this.m_Text9.Width = 91;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.Bold = true;
            this.m_Button5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button5.DelayMouseInputPeriod = 0;
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontFamily = "Arial";
            this.m_Button5.FontSizePixels = 20;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button5.Height = 40;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 701;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Button5.StyleName = "Vintage";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button5.TextHeight = 24;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 34;
            this.m_Button5.Top = 248;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = 1250273231;
            this.m_Button5.Width = 40;
            // 
            // m_Button6
            // 
            this.m_Button6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(129)))), ((int)(((byte)(189))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BlinkDynamicsValue = false;
            this.m_Button6.Bold = true;
            this.m_Button6.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Button6.DelayMouseInputPeriod = 0;
            this.m_Button6.EnabledDynamicsValue = true;
            this.m_Button6.FontFamily = "Arial";
            this.m_Button6.FontSizePixels = 20;
            this.m_Button6.ForceTransparency = true;
            this.m_Button6.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button6.Height = 40;
            this.m_Button6.IndicatorMargin = null;
            this.m_Button6.Left = 702;
            this.m_Button6.Name = "m_Button6";
            this.m_Button6.RequiresTransparency = true;
            this.m_Button6.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Button6.StyleName = "Vintage";
            this.m_Button6.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button6.TextHeight = 24;
            this.m_Button6.TextValue = 0D;
            this.m_Button6.TextWidth = 34;
            this.m_Button6.Top = 320;
            this.m_Button6.Value = 0D;
            this.m_Button6.VisibleDynamicsValue = true;
            this.m_Button6.VisualPropertiesHashCode = 1250273231;
            this.m_Button6.Width = 40;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.Enabled = false;
            this.m_Rectangle.EnabledDynamicsValue = false;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(43)))), ((int)(((byte)(43))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 352;
            this.m_Rectangle.Left = 0;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Top = 0;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 336;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontFamily = "Segoe UI";
            this.m_Text1.FontSizePixels = 16;
            this.m_Text1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 71;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text1.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text1.TextVerticalAlignment = "Center";
            this.m_Text1.Top = 72;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 41;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontFamily = "Segoe UI Semibold";
            this.m_Text3.FontSizePixels = 20;
            this.m_Text3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 24;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text3.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text3.TextVerticalAlignment = "Center";
            this.m_Text3.Top = 16;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 95;
            // 
            // m_SymbolViewbox1
            // 
            this.m_SymbolViewbox1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox1.BlinkDynamicsValue = false;
            this.m_SymbolViewbox1.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox1.EnabledDynamicsValue = true;
            this.m_SymbolViewbox1.ForceTransparency = false;
            this.m_SymbolViewbox1.Height = 32;
            this.m_SymbolViewbox1.IndicatorMargin = null;
            this.m_SymbolViewbox1.Left = 23;
            this.m_SymbolViewbox1.Name = "m_SymbolViewbox1";
            this.m_SymbolViewbox1.RequiresTransparency = false;
            this.m_SymbolViewbox1.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox1.Top = 72;
            this.m_SymbolViewbox1.Value = 0D;
            this.m_SymbolViewbox1.VisibleDynamicsValue = true;
            this.m_SymbolViewbox1.Width = 40;
            // 
            // m_SymbolViewbox
            // 
            this.m_SymbolViewbox.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox.BlinkDynamicsValue = false;
            this.m_SymbolViewbox.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox.EnabledDynamicsValue = true;
            this.m_SymbolViewbox.ForceTransparency = false;
            this.m_SymbolViewbox.Height = 32;
            this.m_SymbolViewbox.IndicatorMargin = null;
            this.m_SymbolViewbox.Left = 23;
            this.m_SymbolViewbox.Name = "m_SymbolViewbox";
            this.m_SymbolViewbox.RequiresTransparency = false;
            this.m_SymbolViewbox.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox.Top = 144;
            this.m_SymbolViewbox.Value = 0D;
            this.m_SymbolViewbox.VisibleDynamicsValue = true;
            this.m_SymbolViewbox.Width = 40;
            // 
            // m_SymbolViewbox2
            // 
            this.m_SymbolViewbox2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox2.BlinkDynamicsValue = false;
            this.m_SymbolViewbox2.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox2.EnabledDynamicsValue = true;
            this.m_SymbolViewbox2.ForceTransparency = false;
            this.m_SymbolViewbox2.Height = 32;
            this.m_SymbolViewbox2.IndicatorMargin = null;
            this.m_SymbolViewbox2.Left = 23;
            this.m_SymbolViewbox2.Name = "m_SymbolViewbox2";
            this.m_SymbolViewbox2.RequiresTransparency = false;
            this.m_SymbolViewbox2.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox2.Top = 216;
            this.m_SymbolViewbox2.Value = 0D;
            this.m_SymbolViewbox2.VisibleDynamicsValue = true;
            this.m_SymbolViewbox2.Width = 40;
            // 
            // m_SymbolViewbox3
            // 
            this.m_SymbolViewbox3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox3.BlinkDynamicsValue = false;
            this.m_SymbolViewbox3.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox3.EnabledDynamicsValue = true;
            this.m_SymbolViewbox3.ForceTransparency = false;
            this.m_SymbolViewbox3.Height = 32;
            this.m_SymbolViewbox3.IndicatorMargin = null;
            this.m_SymbolViewbox3.Left = 23;
            this.m_SymbolViewbox3.Name = "m_SymbolViewbox3";
            this.m_SymbolViewbox3.RequiresTransparency = false;
            this.m_SymbolViewbox3.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox3.Top = 288;
            this.m_SymbolViewbox3.Value = 0D;
            this.m_SymbolViewbox3.VisibleDynamicsValue = true;
            this.m_SymbolViewbox3.Width = 40;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.Bold = true;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontFamily = "Segoe UI";
            this.m_Text2.FontSizePixels = 16;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 71;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text2.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text2.TextVerticalAlignment = "Center";
            this.m_Text2.Top = 144;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 41;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.Bold = true;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontFamily = "Segoe UI";
            this.m_Text4.FontSizePixels = 16;
            this.m_Text4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text4.Height = 21;
            this.m_Text4.Left = 71;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text4.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text4.TextVerticalAlignment = "Center";
            this.m_Text4.Top = 216;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 41;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.Bold = true;
            this.m_Text5.DelayMouseInputPeriod = 0;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontFamily = "Segoe UI";
            this.m_Text5.FontSizePixels = 16;
            this.m_Text5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text5.Height = 21;
            this.m_Text5.Left = 71;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text5.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Text5.TextVerticalAlignment = "Center";
            this.m_Text5.Top = 288;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 41;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "Segoe UI";
            this.m_Button1.FontSizePixels = 15;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 32;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 240;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button1.TextHeight = 20;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 62;
            this.m_Button1.Top = 72;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 54337549;
            this.m_Button1.Width = 72;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button2.DelayMouseInputPeriod = 0;
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontFamily = "Segoe UI";
            this.m_Button2.FontSizePixels = 15;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Height = 32;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 240;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button2.TextHeight = 20;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 62;
            this.m_Button2.Top = 144;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = 54337549;
            this.m_Button2.Width = 72;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button3.DelayMouseInputPeriod = 0;
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontFamily = "Segoe UI";
            this.m_Button3.FontSizePixels = 15;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Height = 32;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 240;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Button3.TextHeight = 20;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 62;
            this.m_Button3.Top = 216;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = 54337549;
            this.m_Button3.Width = 72;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button4.DelayMouseInputPeriod = 0;
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontFamily = "Segoe UI";
            this.m_Button4.FontSizePixels = 15;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Height = 32;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 240;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button4.TextHeight = 20;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 62;
            this.m_Button4.Top = 288;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = 54337549;
            this.m_Button4.Width = 72;
            // 
            // m_Group1
            // 
            this.m_Group1.BlinkDynamicsValue = false;
            this.m_Group1.Components.Add(this.m_Rectangle);
            this.m_Group1.Components.Add(this.m_Text1);
            this.m_Group1.Components.Add(this.m_Text3);
            this.m_Group1.Components.Add(this.m_SymbolViewbox1);
            this.m_Group1.Components.Add(this.m_SymbolViewbox);
            this.m_Group1.Components.Add(this.m_SymbolViewbox2);
            this.m_Group1.Components.Add(this.m_SymbolViewbox3);
            this.m_Group1.Components.Add(this.m_Text2);
            this.m_Group1.Components.Add(this.m_Text4);
            this.m_Group1.Components.Add(this.m_Text5);
            this.m_Group1.Components.Add(this.m_Button1);
            this.m_Group1.Components.Add(this.m_Button2);
            this.m_Group1.Components.Add(this.m_Button3);
            this.m_Group1.Components.Add(this.m_Button4);
            this.m_Group1.DelayMouseInputPeriod = 0;
            this.m_Group1.EnabledDynamicsValue = true;
            this.m_Group1.Height = 352;
            this.m_Group1.Left = 80;
            this.m_Group1.Name = "m_Group1";
            this.m_Group1.ParentGroup = null;
            this.m_Group1.ScreenOwnerName = "DiagnosticsScreen";
            this.m_Group1.Top = 112;
            this.m_Group1.VisibleDynamicsValue = true;
            this.m_Group1.Width = 336;
            // 
            // m_SymbolViewbox7
            // 
            this.m_SymbolViewbox7.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox7.BlinkDynamicsValue = false;
            this.m_SymbolViewbox7.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox7.EnabledDynamicsValue = true;
            this.m_SymbolViewbox7.ForceTransparency = false;
            this.m_SymbolViewbox7.Height = 32;
            this.m_SymbolViewbox7.IndicatorMargin = null;
            this.m_SymbolViewbox7.Left = 103;
            this.m_SymbolViewbox7.Name = "m_SymbolViewbox7";
            this.m_SymbolViewbox7.RequiresTransparency = true;
            this.m_SymbolViewbox7.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox7.Top = 184;
            this.m_SymbolViewbox7.Value = 0D;
            this.m_SymbolViewbox7.VisibleDynamicsValue = true;
            this.m_SymbolViewbox7.Width = 40;
            // 
            // m_SymbolViewbox8
            // 
            this.m_SymbolViewbox8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox8.BlinkDynamicsValue = false;
            this.m_SymbolViewbox8.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox8.EnabledDynamicsValue = true;
            this.m_SymbolViewbox8.ForceTransparency = false;
            this.m_SymbolViewbox8.Height = 32;
            this.m_SymbolViewbox8.IndicatorMargin = null;
            this.m_SymbolViewbox8.Left = 103;
            this.m_SymbolViewbox8.Name = "m_SymbolViewbox8";
            this.m_SymbolViewbox8.RequiresTransparency = true;
            this.m_SymbolViewbox8.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox8.Top = 256;
            this.m_SymbolViewbox8.Value = 0D;
            this.m_SymbolViewbox8.VisibleDynamicsValue = true;
            this.m_SymbolViewbox8.Width = 40;
            // 
            // m_SymbolViewbox9
            // 
            this.m_SymbolViewbox9.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox9.BlinkDynamicsValue = false;
            this.m_SymbolViewbox9.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox9.EnabledDynamicsValue = true;
            this.m_SymbolViewbox9.ForceTransparency = false;
            this.m_SymbolViewbox9.Height = 32;
            this.m_SymbolViewbox9.IndicatorMargin = null;
            this.m_SymbolViewbox9.Left = 103;
            this.m_SymbolViewbox9.Name = "m_SymbolViewbox9";
            this.m_SymbolViewbox9.RequiresTransparency = true;
            this.m_SymbolViewbox9.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox9.Top = 328;
            this.m_SymbolViewbox9.Value = 0D;
            this.m_SymbolViewbox9.VisibleDynamicsValue = true;
            this.m_SymbolViewbox9.Width = 40;
            // 
            // m_SymbolViewbox10
            // 
            this.m_SymbolViewbox10.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox10.BlinkDynamicsValue = false;
            this.m_SymbolViewbox10.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox10.EnabledDynamicsValue = true;
            this.m_SymbolViewbox10.ForceTransparency = false;
            this.m_SymbolViewbox10.Height = 32;
            this.m_SymbolViewbox10.IndicatorMargin = null;
            this.m_SymbolViewbox10.Left = 103;
            this.m_SymbolViewbox10.Name = "m_SymbolViewbox10";
            this.m_SymbolViewbox10.RequiresTransparency = true;
            this.m_SymbolViewbox10.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox10.Top = 400;
            this.m_SymbolViewbox10.Value = 0D;
            this.m_SymbolViewbox10.VisibleDynamicsValue = true;
            this.m_SymbolViewbox10.Width = 40;
            // 
            // m_SymbolViewbox11
            // 
            this.m_SymbolViewbox11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox11.BlinkDynamicsValue = false;
            this.m_SymbolViewbox11.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox11.EnabledDynamicsValue = true;
            this.m_SymbolViewbox11.ForceTransparency = false;
            this.m_SymbolViewbox11.Height = 32;
            this.m_SymbolViewbox11.IndicatorMargin = null;
            this.m_SymbolViewbox11.Left = 456;
            this.m_SymbolViewbox11.Name = "m_SymbolViewbox11";
            this.m_SymbolViewbox11.RequiresTransparency = true;
            this.m_SymbolViewbox11.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox11.Top = 184;
            this.m_SymbolViewbox11.Value = 0D;
            this.m_SymbolViewbox11.VisibleDynamicsValue = true;
            this.m_SymbolViewbox11.Width = 40;
            // 
            // m_SymbolViewbox12
            // 
            this.m_SymbolViewbox12.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox12.BlinkDynamicsValue = false;
            this.m_SymbolViewbox12.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox12.EnabledDynamicsValue = true;
            this.m_SymbolViewbox12.ForceTransparency = false;
            this.m_SymbolViewbox12.Height = 32;
            this.m_SymbolViewbox12.IndicatorMargin = null;
            this.m_SymbolViewbox12.Left = 456;
            this.m_SymbolViewbox12.Name = "m_SymbolViewbox12";
            this.m_SymbolViewbox12.RequiresTransparency = true;
            this.m_SymbolViewbox12.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox12.Top = 256;
            this.m_SymbolViewbox12.Value = 0D;
            this.m_SymbolViewbox12.VisibleDynamicsValue = true;
            this.m_SymbolViewbox12.Width = 40;
            // 
            // m_SymbolViewbox13
            // 
            this.m_SymbolViewbox13.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.White, System.Drawing.Color.White, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolViewbox13.BlinkDynamicsValue = false;
            this.m_SymbolViewbox13.DelayMouseInputPeriod = 0;
            this.m_SymbolViewbox13.EnabledDynamicsValue = true;
            this.m_SymbolViewbox13.ForceTransparency = false;
            this.m_SymbolViewbox13.Height = 32;
            this.m_SymbolViewbox13.IndicatorMargin = null;
            this.m_SymbolViewbox13.Left = 456;
            this.m_SymbolViewbox13.Name = "m_SymbolViewbox13";
            this.m_SymbolViewbox13.RequiresTransparency = true;
            this.m_SymbolViewbox13.ScreenOwnerName = "DiagnosticsScreen";
            this.m_SymbolViewbox13.Top = 328;
            this.m_SymbolViewbox13.Value = 0D;
            this.m_SymbolViewbox13.VisibleDynamicsValue = true;
            this.m_SymbolViewbox13.Width = 40;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "DiagnosticsScreen";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_DiagnosticsScreen = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
            this.SecurityGroups = SecurityGroups.Group_01 | SecurityGroups.Group_02;
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_Rectangle, SecurityGroups.Group_01 | SecurityGroups.Group_02);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_DiagnosticsScreen) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_Text7);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox4);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox5);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox6);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Text9);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Button6);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox1);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox2);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox3);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Group1);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox7);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox8);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox9);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox10);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox11);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox12);
            this.DrawingPrimitives.Add(this.m_SymbolViewbox13);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).EndInit();
            base.AddDrawingPrimitives();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Set Analog", "Tags.HMI_Fault_ErrorCode", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Fault_ErrorCode.SetAnalog(1001);
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "FaultDialog", "");
            Neo.ApplicationFramework.Generated.Globals.FaultDialog.Show();
        }
        
        private void m_Button5_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "Click", "Set Analog", "Tags.HMI_Fault_ErrorCode", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Fault_ErrorCode.SetAnalog(1002);
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "Click", "Show Screen", "FaultDialog", "");
            Neo.ApplicationFramework.Generated.Globals.FaultDialog.Show();
        }
        
        private void m_Button6_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "Click", "Set Analog", "Tags.HMI_Fault_ErrorCode", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Fault_ErrorCode.SetAnalog(1003);
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "Click", "Show Screen", "FaultDialog", "");
            Neo.ApplicationFramework.Generated.Globals.FaultDialog.Show();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Set Tag", "Tags.HMI_Elevator_ResetFloor4", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor4.SetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Reset Tag", "Tags.HMI_Elevator_ResetFloor4", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor4.ResetTag();
        }
        
        private void m_Button2_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "Click", "Set Tag", "Tags.HMI_Elevator_ResetFloor3", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor3.SetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "Click", "Reset Tag", "Tags.HMI_Elevator_ResetFloor3", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor3.ResetTag();
        }
        
        private void m_Button3_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "Click", "Set Tag", "Tags.HMI_Elevator_ResetFloor2", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor2.SetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "Click", "Reset Tag", "Tags.HMI_Elevator_ResetFloor2", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor2.ResetTag();
        }
        
        private void m_Button4_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "Click", "Set Tag", "Tags.HMI_Elevator_ResetFloor1", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor1.SetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "Click", "Reset Tag", "Tags.HMI_Elevator_ResetFloor1", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_ResetFloor1.ResetTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DiagnosticsScreen));
            this.m_Text.Text = resources.GetText("DiagnosticsScreen.Text.Text", "Diagnostics");
            this.m_Button.Text = resources.GetText("DiagnosticsScreen.Button.Text", "?");
            this.m_Text6.Text = resources.GetText("DiagnosticsScreen.Text6.Text", "Fault Status");
            this.m_Text1.Text = resources.GetText("DiagnosticsScreen.Text1.Text", "Floor 4");
            this.m_Text3.Text = resources.GetText("DiagnosticsScreen.Text3.Text", "Maintanence Alert");
            this.m_Text2.Text = resources.GetText("DiagnosticsScreen.Text2.Text", "Floor 3");
            this.m_Text4.Text = resources.GetText("DiagnosticsScreen.Text4.Text", "Floor 2");
            this.m_Text5.Text = resources.GetText("DiagnosticsScreen.Text5.Text", "Floor 1");
            this.m_Button1.Text = resources.GetText("DiagnosticsScreen.Button1.Text", "RESET");
            this.m_Button2.Text = resources.GetText("DiagnosticsScreen.Button2.Text", "RESET");
            this.m_Button3.Text = resources.GetText("DiagnosticsScreen.Button3.Text", "RESET");
            this.m_Button4.Text = resources.GetText("DiagnosticsScreen.Button4.Text", "RESET");
            this.m_Text7.Text = resources.GetText("DiagnosticsScreen.Text7.Text", "Error Code: 1001");
            this.m_Text8.Text = resources.GetText("DiagnosticsScreen.Text8.Text", "Error Code: 1002");
            this.m_Text9.Text = resources.GetText("DiagnosticsScreen.Text9.Text", "Error Code: 1003");
            this.m_Button5.Text = resources.GetText("DiagnosticsScreen.Button5.Text", "?");
            this.m_Button6.Text = resources.GetText("DiagnosticsScreen.Button6.Text", "?");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_DiagnosticsScreen) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MaintenanceRequiredFloor4"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_SymbolViewbox7.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MaintenanceRequiredFloor3"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_SymbolViewbox8.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MaintenanceRequiredFloor2"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_SymbolViewbox9.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.MaintenanceRequiredFloor1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_SymbolViewbox10.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_SharedData_Fault_Status_1001"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_SymbolViewbox11.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_SharedData_Fault_Status_1002"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_SymbolViewbox12.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_SharedData_Fault_Status_1003"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_SymbolViewbox13.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
        }
    }
}
