//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class FaultDialog : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Title;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.TextBox m_TextBox;
        
        private Neo.ApplicationFramework.Controls.Controls.TextBox m_TextBox1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private bool m_Initialized_FaultDialog;
        
        private Neo.ApplicationFramework.Common.Dynamics.MessageLibraryDynamicsConverterCF messagelibrarydynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.MessageLibraryDynamicsConverterCF messagelibrarydynamicsconvertercf2;
        
        public FaultDialog() {
            this.InitializeComponent();
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Title {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Title);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter TextBox {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter>(this.m_TextBox);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter TextBox1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextBoxCFAdapter>(this.m_TextBox1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        private void InitializeComponent() {
            this.messagelibrarydynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.MessageLibraryDynamicsConverterCF();
            this.messagelibrarydynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.MessageLibraryDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.MessageLibraryGroupResolver messagelibrarygroupresolver1 = new Neo.ApplicationFramework.Common.Dynamics.MessageLibraryGroupResolver();
            Neo.ApplicationFramework.Common.Dynamics.MessageLibraryGroupResolver messagelibrarygroupresolver2 = new Neo.ApplicationFramework.Common.Dynamics.MessageLibraryGroupResolver();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Title = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_TextBox = new Neo.ApplicationFramework.Controls.Controls.TextBox();
            this.m_TextBox1 = new Neo.ApplicationFramework.Controls.Controls.TextBox();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_Title)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TextBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TextBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            this.SuspendLayout();
            // 
            // FaultDialog
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.DelayMouseInputPeriod = 0;
            this.m_Rectangle2.Enabled = false;
            this.m_Rectangle2.EnabledDynamicsValue = false;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(43)))), ((int)(((byte)(43))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 321;
            this.m_Rectangle2.Left = 184;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "FaultDialog";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle2.StrokeThickness = 0;
            this.m_Rectangle2.Top = 80;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 432;
            // 
            // m_Title
            // 
            this.m_Title.BlinkDynamicsValue = false;
            this.m_Title.Bold = true;
            this.m_Title.DelayMouseInputPeriod = 0;
            this.m_Title.EnabledDynamicsValue = true;
            this.m_Title.FontFamily = "Segoe UI";
            this.m_Title.FontSizePixels = 24;
            this.m_Title.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Title.Height = 21;
            this.m_Title.Left = 216;
            this.m_Title.Name = "m_Title";
            this.m_Title.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(6D, 0D, 6D, 1D);
            this.m_Title.ScreenOwnerName = "FaultDialog";
            this.m_Title.Top = 97;
            this.m_Title.VisibleDynamicsValue = true;
            this.m_Title.Width = 63;
            // 
            // m_Button
            // 
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "Segoe UI";
            this.m_Button.FontSizePixels = 18;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(146)))), ((int)(((byte)(214)))));
            this.m_Button.Height = 40;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 504;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "FaultDialog";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 25;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 90;
            this.m_Button.Top = 337;
            this.m_Button.Transparent = true;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -943958308;
            this.m_Button.Width = 100;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.Bold = true;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontFamily = "Segoe UI";
            this.m_Text3.FontSizePixels = 24;
            this.m_Text3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text3.Height = 6;
            this.m_Text3.Left = 351;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(6D, 0D, 6D, 1D);
            this.m_Text3.ScreenOwnerName = "FaultDialog";
            this.m_Text3.Top = 98;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 4;
            // 
            // m_TextBox
            // 
            this.m_TextBox.BlinkDynamicsValue = false;
            this.m_TextBox.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            messagelibrarydynamicsconvertercf1.MessageLibraryGroupName = "Fault_Description";
            messagelibrarydynamicsconvertercf1.MessageLibraryGroupResolver = messagelibrarygroupresolver1;
            this.m_TextBox.DelayMouseInputPeriod = 0;
            this.m_TextBox.EnabledDynamicsValue = true;
            this.m_TextBox.FontFamily = "Segoe UI";
            this.m_TextBox.FontSizePixels = 20;
            this.m_TextBox.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_TextBox.Height = 64;
            this.m_TextBox.Left = 218;
            this.m_TextBox.MultiLine = true;
            this.m_TextBox.Name = "m_TextBox";
            this.m_TextBox.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_TextBox.ReadOnly = true;
            this.m_TextBox.ScreenOwnerName = "FaultDialog";
            this.m_TextBox.Top = 177;
            this.m_TextBox.VisibleDynamicsValue = true;
            this.m_TextBox.Width = 352;
            this.m_TextBox.WordWrap = true;
            // 
            // m_TextBox1
            // 
            this.m_TextBox1.BlinkDynamicsValue = false;
            this.m_TextBox1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            messagelibrarydynamicsconvertercf2.MessageLibraryGroupName = "Fault_Causes";
            messagelibrarydynamicsconvertercf2.MessageLibraryGroupResolver = messagelibrarygroupresolver2;
            this.m_TextBox1.DelayMouseInputPeriod = 0;
            this.m_TextBox1.EnabledDynamicsValue = true;
            this.m_TextBox1.FontFamily = "Segoe UI";
            this.m_TextBox1.FontSizePixels = 20;
            this.m_TextBox1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_TextBox1.Height = 64;
            this.m_TextBox1.Left = 219;
            this.m_TextBox1.MultiLine = true;
            this.m_TextBox1.Name = "m_TextBox1";
            this.m_TextBox1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_TextBox1.ReadOnly = true;
            this.m_TextBox1.ScreenOwnerName = "FaultDialog";
            this.m_TextBox1.Top = 273;
            this.m_TextBox1.VisibleDynamicsValue = true;
            this.m_TextBox1.Width = 352;
            this.m_TextBox1.WordWrap = true;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "Segoe UI";
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text.Height = 21;
            this.m_Text.Left = 216;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text.ScreenOwnerName = "FaultDialog";
            this.m_Text.Top = 145;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 65;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontFamily = "Segoe UI";
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 216;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text1.ScreenOwnerName = "FaultDialog";
            this.m_Text1.Top = 241;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 87;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "FaultDialog";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_FaultDialog = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
            this.SecurityGroups = SecurityGroups.Group_01 | SecurityGroups.Group_02;
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_FaultDialog) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Title);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_TextBox);
            this.DrawingPrimitives.Add(this.m_TextBox1);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            ((System.ComponentModel.ISupportInitialize)(this.m_Title)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TextBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_TextBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            this.LogClose("m_Button", "Click", "Close Screen", "");
            this.Close();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(FaultDialog));
            this.m_Title.Text = resources.GetText("FaultDialog.Title.Text", "Error Code:");
            this.m_Button.Text = resources.GetText("FaultDialog.Button.Text", "OK");
            this.m_Text.Text = resources.GetText("FaultDialog.Text.Text", "Description:");
            this.m_Text1.Text = resources.GetText("FaultDialog.Text1.Text", "Possible causes:");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_FaultDialog) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Text", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Fault_ErrorCode"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.RawConverterCF.Default);
            this.m_Text3.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Text", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Fault_ErrorCode"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, messagelibrarydynamicsconvertercf1);
            this.m_TextBox.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Text", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Fault_ErrorCode"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, messagelibrarydynamicsconvertercf2);
            this.m_TextBox1.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
        }
    }
}
