//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class MainScreen : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_MenuBar;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Box_Overview;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button_Overview;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Menu_Overview;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Bar_Menu;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Menu_Diagnostics;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Box_Diagnostics;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button_Diagnostics;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Menu_LogIn;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Box_LogIn;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button_LogIn;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Menu_Settings;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Box_Settings;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button_Settings;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Menu_Admin;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Box_Admin;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button_Admin;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_StatusBar;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Time;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Status;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Bar_Status;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_User;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture5;
        
        private bool m_Initialized_MainScreen;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf3;
        
        private Neo.ApplicationFramework.Common.Dynamics.MessageLibraryDynamicsConverterCF messagelibrarydynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf4;
        
        public MainScreen() {
            this.InitializeComponent();
            this.m_Button_Overview.Click += new System.EventHandler(this.m_Button_Overview_Action_Click);
            this.m_Button_Diagnostics.Click += new System.EventHandler(this.m_Button_Diagnostics_Action_Click);
            this.m_Button_LogIn.Click += new System.EventHandler(this.m_Button_LogIn_Action_Click);
            this.m_Button_Settings.Click += new System.EventHandler(this.m_Button_Settings_Action_Click);
            this.m_Button_Admin.Click += new System.EventHandler(this.m_Button_Admin_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Bar_Menu {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Bar_Menu);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter MenuBar {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_MenuBar);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Menu_Overview {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Menu_Overview);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Box_Overview {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Box_Overview);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button_Overview {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button_Overview);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Menu_Diagnostics {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Menu_Diagnostics);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Box_Diagnostics {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Box_Diagnostics);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button_Diagnostics {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button_Diagnostics);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Menu_LogIn {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Menu_LogIn);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Box_LogIn {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Box_LogIn);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button_LogIn {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button_LogIn);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Menu_Settings {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Menu_Settings);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Box_Settings {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Box_Settings);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button_Settings {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button_Settings);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Menu_Admin {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Menu_Admin);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Box_Admin {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Box_Admin);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button_Admin {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button_Admin);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Bar_Status {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Bar_Status);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter StatusBar {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_StatusBar);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Time {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Time);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Status {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Status);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter User {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_User);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture5);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf4 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.messagelibrarydynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.MessageLibraryDynamicsConverterCF();
            this.brushdynamicsconvertercf3 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval5 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval6 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval7 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval8 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval9 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.MessageLibraryGroupResolver messagelibrarygroupresolver1 = new Neo.ApplicationFramework.Common.Dynamics.MessageLibraryGroupResolver();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval10 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval11 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval12 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval13 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            this.m_MenuBar = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Box_Overview = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button_Overview = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Menu_Overview = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Bar_Menu = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Menu_Diagnostics = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Box_Diagnostics = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button_Diagnostics = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Menu_LogIn = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Box_LogIn = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button_LogIn = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Menu_Settings = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Box_Settings = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button_Settings = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Menu_Admin = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Box_Admin = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button_Admin = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_StatusBar = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Time = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Ellipse = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Status = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Bar_Status = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_User = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture5 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Overview)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Overview)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Bar_Menu)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Diagnostics)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Diagnostics)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_LogIn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_LogIn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Settings)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Settings)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Admin)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Admin)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Time)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Status)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Bar_Status)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_User)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).BeginInit();
            this.SuspendLayout();
            // 
            // MainScreen
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(18)))), ((int)(((byte)(18))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_MenuBar
            // 
            this.m_MenuBar.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_MenuBar.BlinkDynamicsValue = false;
            this.m_MenuBar.DelayMouseInputPeriod = 0;
            this.m_MenuBar.Enabled = false;
            this.m_MenuBar.EnabledDynamicsValue = false;
            this.m_MenuBar.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_MenuBar.Height = 416;
            this.m_MenuBar.Left = 0;
            this.m_MenuBar.Name = "m_MenuBar";
            this.m_MenuBar.ScreenOwnerName = "MainScreen";
            this.m_MenuBar.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_MenuBar.StrokeThickness = 0;
            this.m_MenuBar.Top = 0;
            this.m_MenuBar.VisibleDynamicsValue = true;
            this.m_MenuBar.Width = 64;
            // 
            // m_Box_Overview
            // 
            this.m_Box_Overview.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Box_Overview.BlinkDynamicsValue = false;
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(98)))), ((int)(((byte)(109))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(98)))), ((int)(((byte)(109))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.End = 2D;
            brushcfinterval3.Start = 2D;
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            this.m_Box_Overview.DelayMouseInputPeriod = 0;
            this.m_Box_Overview.Enabled = false;
            this.m_Box_Overview.EnabledDynamicsValue = false;
            this.m_Box_Overview.Fill = null;
            this.m_Box_Overview.Height = 64;
            this.m_Box_Overview.Left = 0;
            this.m_Box_Overview.Name = "m_Box_Overview";
            this.m_Box_Overview.ScreenOwnerName = "MainScreen";
            this.m_Box_Overview.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Box_Overview.StrokeThickness = 0;
            this.m_Box_Overview.Top = 0;
            this.m_Box_Overview.VisibleDynamicsValue = true;
            this.m_Box_Overview.Width = 64;
            // 
            // m_Button_Overview
            // 
            this.m_Button_Overview.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button_Overview.BlinkDynamicsValue = false;
            this.m_Button_Overview.DelayMouseInputPeriod = 0;
            this.m_Button_Overview.EnabledDynamicsValue = true;
            this.m_Button_Overview.FontSizePixels = 15;
            this.m_Button_Overview.ForceTransparency = true;
            this.m_Button_Overview.Height = 64;
            this.m_Button_Overview.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(10D, 10D, 10D, 10D);
            this.m_Button_Overview.IndicatorMargin = null;
            this.m_Button_Overview.Left = 0;
            this.m_Button_Overview.Name = "m_Button_Overview";
            this.m_Button_Overview.RequiresTransparency = true;
            this.m_Button_Overview.ScreenOwnerName = "MainScreen";
            this.m_Button_Overview.SymbolHeight = 34;
            this.m_Button_Overview.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button_Overview.SymbolName = "ic_overview (2)";
            this.m_Button_Overview.SymbolWidth = 40;
            this.m_Button_Overview.TextHeight = 18;
            this.m_Button_Overview.TextMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_Button_Overview.TextValue = 0D;
            this.m_Button_Overview.TextWidth = 60;
            this.m_Button_Overview.Top = 0;
            this.m_Button_Overview.Transparent = true;
            this.m_Button_Overview.Value = 0D;
            this.m_Button_Overview.VisibleDynamicsValue = true;
            this.m_Button_Overview.VisualPropertiesHashCode = -930482324;
            this.m_Button_Overview.Width = 64;
            // 
            // m_Menu_Overview
            // 
            this.m_Menu_Overview.BlinkDynamicsValue = false;
            this.m_Menu_Overview.Components.Add(this.m_Box_Overview);
            this.m_Menu_Overview.Components.Add(this.m_Button_Overview);
            this.m_Menu_Overview.DelayMouseInputPeriod = 0;
            this.m_Menu_Overview.EnabledDynamicsValue = true;
            this.m_Menu_Overview.Height = 64;
            this.m_Menu_Overview.Left = 0;
            this.m_Menu_Overview.Name = "m_Menu_Overview";
            // 
            // m_Bar_Menu
            // 
            this.m_Bar_Menu.BlinkDynamicsValue = false;
            // 
            // m_Menu_Diagnostics
            // 
            this.m_Menu_Diagnostics.BlinkDynamicsValue = false;
            // 
            // m_Box_Diagnostics
            // 
            this.m_Box_Diagnostics.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Box_Diagnostics.BlinkDynamicsValue = false;
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval5.End = 1D;
            brushcfinterval5.Start = 1D;
            brushcfinterval5.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(98)))), ((int)(((byte)(109))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval6.End = 2D;
            brushcfinterval6.Start = 2D;
            brushcfinterval6.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval5);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval6);
            this.m_Box_Diagnostics.DelayMouseInputPeriod = 0;
            this.m_Box_Diagnostics.Enabled = false;
            this.m_Box_Diagnostics.EnabledDynamicsValue = false;
            this.m_Box_Diagnostics.Fill = null;
            this.m_Box_Diagnostics.Height = 64;
            this.m_Box_Diagnostics.Left = 0;
            this.m_Box_Diagnostics.Name = "m_Box_Diagnostics";
            this.m_Box_Diagnostics.ScreenOwnerName = "MainScreen";
            this.m_Box_Diagnostics.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Box_Diagnostics.StrokeThickness = 0;
            this.m_Box_Diagnostics.Top = 0;
            this.m_Box_Diagnostics.VisibleDynamicsValue = true;
            this.m_Box_Diagnostics.Width = 64;
            // 
            // m_Button_Diagnostics
            // 
            this.m_Button_Diagnostics.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button_Diagnostics.BlinkDynamicsValue = false;
            this.m_Button_Diagnostics.DelayMouseInputPeriod = 0;
            this.m_Button_Diagnostics.EnabledDynamicsValue = true;
            this.m_Button_Diagnostics.FontSizePixels = 15;
            this.m_Button_Diagnostics.ForceTransparency = true;
            this.m_Button_Diagnostics.Height = 64;
            this.m_Button_Diagnostics.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(14D, 14D, 14D, 14D);
            this.m_Button_Diagnostics.IndicatorMargin = null;
            this.m_Button_Diagnostics.Left = 0;
            this.m_Button_Diagnostics.Name = "m_Button_Diagnostics";
            this.m_Button_Diagnostics.RequiresTransparency = true;
            this.m_Button_Diagnostics.ScreenOwnerName = "MainScreen";
            this.m_Button_Diagnostics.SymbolHeight = 32;
            this.m_Button_Diagnostics.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button_Diagnostics.SymbolName = "ic_diagnostics";
            this.m_Button_Diagnostics.SymbolWidth = 32;
            this.m_Button_Diagnostics.TextHeight = 18;
            this.m_Button_Diagnostics.TextMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_Button_Diagnostics.TextValue = 0D;
            this.m_Button_Diagnostics.TextWidth = 60;
            this.m_Button_Diagnostics.Top = 0;
            this.m_Button_Diagnostics.Transparent = true;
            this.m_Button_Diagnostics.Value = 0D;
            this.m_Button_Diagnostics.VisibleDynamicsValue = true;
            this.m_Button_Diagnostics.VisualPropertiesHashCode = -1868312845;
            this.m_Button_Diagnostics.Width = 64;
            this.m_Menu_Diagnostics.Components.Add(this.m_Box_Diagnostics);
            this.m_Menu_Diagnostics.Components.Add(this.m_Button_Diagnostics);
            this.m_Menu_Diagnostics.DelayMouseInputPeriod = 0;
            this.m_Menu_Diagnostics.EnabledDynamicsValue = true;
            this.m_Menu_Diagnostics.Height = 64;
            this.m_Menu_Diagnostics.Left = 0;
            this.m_Menu_Diagnostics.Name = "m_Menu_Diagnostics";
            this.m_Menu_Diagnostics.ParentGroup = this.m_Bar_Menu;
            this.m_Menu_Diagnostics.ScreenOwnerName = "MainScreen";
            this.m_Menu_Diagnostics.Top = 64;
            this.m_Menu_Diagnostics.VisibleDynamicsValue = true;
            this.m_Menu_Diagnostics.Width = 64;
            // 
            // m_Menu_LogIn
            // 
            this.m_Menu_LogIn.BlinkDynamicsValue = false;
            // 
            // m_Box_LogIn
            // 
            this.m_Box_LogIn.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Box_LogIn.BlinkDynamicsValue = false;
            this.m_Box_LogIn.DelayMouseInputPeriod = 0;
            this.m_Box_LogIn.Enabled = false;
            this.m_Box_LogIn.EnabledDynamicsValue = false;
            this.m_Box_LogIn.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Box_LogIn.Height = 64;
            this.m_Box_LogIn.Left = 0;
            this.m_Box_LogIn.Name = "m_Box_LogIn";
            this.m_Box_LogIn.ScreenOwnerName = "MainScreen";
            this.m_Box_LogIn.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Box_LogIn.StrokeThickness = 0;
            this.m_Box_LogIn.Top = 0;
            this.m_Box_LogIn.VisibleDynamicsValue = true;
            this.m_Box_LogIn.Width = 64;
            // 
            // m_Button_LogIn
            // 
            this.m_Button_LogIn.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button_LogIn.BlinkDynamicsValue = false;
            this.m_Button_LogIn.DelayMouseInputPeriod = 0;
            this.m_Button_LogIn.EnabledDynamicsValue = true;
            this.m_Button_LogIn.FontSizePixels = 15;
            this.m_Button_LogIn.ForceTransparency = true;
            this.m_Button_LogIn.Height = 64;
            this.m_Button_LogIn.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(14D, 14D, 14D, 14D);
            this.m_Button_LogIn.IndicatorMargin = null;
            this.m_Button_LogIn.Left = 0;
            this.m_Button_LogIn.Name = "m_Button_LogIn";
            this.m_Button_LogIn.RequiresTransparency = true;
            this.m_Button_LogIn.ScreenOwnerName = "MainScreen";
            this.m_Button_LogIn.SymbolHeight = 32;
            this.m_Button_LogIn.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button_LogIn.SymbolName = "ic_login";
            this.m_Button_LogIn.SymbolWidth = 31;
            this.m_Button_LogIn.TextHeight = 18;
            this.m_Button_LogIn.TextMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_Button_LogIn.TextValue = 0D;
            this.m_Button_LogIn.TextWidth = 60;
            this.m_Button_LogIn.Top = 0;
            this.m_Button_LogIn.Transparent = true;
            this.m_Button_LogIn.Value = 0D;
            this.m_Button_LogIn.VisibleDynamicsValue = true;
            this.m_Button_LogIn.VisualPropertiesHashCode = 1185767015;
            this.m_Button_LogIn.Width = 64;
            this.m_Menu_LogIn.Components.Add(this.m_Box_LogIn);
            this.m_Menu_LogIn.Components.Add(this.m_Button_LogIn);
            this.m_Menu_LogIn.DelayMouseInputPeriod = 0;
            this.m_Menu_LogIn.EnabledDynamicsValue = true;
            this.m_Menu_LogIn.Height = 64;
            this.m_Menu_LogIn.Left = 0;
            this.m_Menu_LogIn.Name = "m_Menu_LogIn";
            this.m_Menu_LogIn.ParentGroup = this.m_Bar_Menu;
            this.m_Menu_LogIn.ScreenOwnerName = "MainScreen";
            this.m_Menu_LogIn.Top = 288;
            this.m_Menu_LogIn.VisibleDynamicsValue = true;
            this.m_Menu_LogIn.Width = 64;
            // 
            // m_Menu_Settings
            // 
            this.m_Menu_Settings.BlinkDynamicsValue = false;
            // 
            // m_Box_Settings
            // 
            this.m_Box_Settings.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Box_Settings.BlinkDynamicsValue = false;
            this.m_Box_Settings.DelayMouseInputPeriod = 0;
            this.m_Box_Settings.Enabled = false;
            this.m_Box_Settings.EnabledDynamicsValue = false;
            this.m_Box_Settings.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Box_Settings.Height = 64;
            this.m_Box_Settings.Left = 0;
            this.m_Box_Settings.Name = "m_Box_Settings";
            this.m_Box_Settings.ScreenOwnerName = "MainScreen";
            this.m_Box_Settings.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Box_Settings.StrokeThickness = 0;
            this.m_Box_Settings.Top = 0;
            this.m_Box_Settings.VisibleDynamicsValue = true;
            this.m_Box_Settings.Width = 64;
            // 
            // m_Button_Settings
            // 
            this.m_Button_Settings.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button_Settings.BlinkDynamicsValue = false;
            this.m_Button_Settings.DelayMouseInputPeriod = 0;
            this.m_Button_Settings.EnabledDynamicsValue = true;
            this.m_Button_Settings.FontSizePixels = 15;
            this.m_Button_Settings.ForceTransparency = true;
            this.m_Button_Settings.Height = 64;
            this.m_Button_Settings.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(14D, 14D, 14D, 14D);
            this.m_Button_Settings.IndicatorMargin = null;
            this.m_Button_Settings.Left = 0;
            this.m_Button_Settings.Name = "m_Button_Settings";
            this.m_Button_Settings.RequiresTransparency = true;
            this.m_Button_Settings.ScreenOwnerName = "MainScreen";
            this.m_Button_Settings.SymbolHeight = 32;
            this.m_Button_Settings.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button_Settings.SymbolName = "ic_settings";
            this.m_Button_Settings.SymbolWidth = 32;
            this.m_Button_Settings.TextHeight = 18;
            this.m_Button_Settings.TextMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_Button_Settings.TextValue = 0D;
            this.m_Button_Settings.TextWidth = 60;
            this.m_Button_Settings.Top = 0;
            this.m_Button_Settings.Transparent = true;
            this.m_Button_Settings.Value = 0D;
            this.m_Button_Settings.VisibleDynamicsValue = true;
            this.m_Button_Settings.VisualPropertiesHashCode = -538090155;
            this.m_Button_Settings.Width = 64;
            this.m_Menu_Settings.Components.Add(this.m_Box_Settings);
            this.m_Menu_Settings.Components.Add(this.m_Button_Settings);
            this.m_Menu_Settings.DelayMouseInputPeriod = 0;
            this.m_Menu_Settings.EnabledDynamicsValue = true;
            this.m_Menu_Settings.Height = 64;
            this.m_Menu_Settings.Left = 0;
            this.m_Menu_Settings.Name = "m_Menu_Settings";
            this.m_Menu_Settings.ParentGroup = this.m_Bar_Menu;
            this.m_Menu_Settings.ScreenOwnerName = "MainScreen";
            this.m_Menu_Settings.Top = 352;
            this.m_Menu_Settings.VisibleDynamicsValue = true;
            this.m_Menu_Settings.Width = 64;
            // 
            // m_Menu_Admin
            // 
            this.m_Menu_Admin.BlinkDynamicsValue = false;
            // 
            // m_Box_Admin
            // 
            this.m_Box_Admin.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Box_Admin.BlinkDynamicsValue = false;
            brushdynamicsconvertercf3.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval7.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval8.End = 1D;
            brushcfinterval8.Start = 1D;
            brushcfinterval8.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(59)))), ((int)(((byte)(73))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval9.End = 2D;
            brushcfinterval9.Start = 2D;
            brushcfinterval9.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(98)))), ((int)(((byte)(109))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval7);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval8);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval9);
            this.m_Box_Admin.DelayMouseInputPeriod = 0;
            this.m_Box_Admin.Enabled = false;
            this.m_Box_Admin.EnabledDynamicsValue = false;
            this.m_Box_Admin.Fill = null;
            this.m_Box_Admin.Height = 64;
            this.m_Box_Admin.Left = 0;
            this.m_Box_Admin.Name = "m_Box_Admin";
            this.m_Box_Admin.ScreenOwnerName = "MainScreen";
            this.m_Box_Admin.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Box_Admin.StrokeThickness = 0;
            this.m_Box_Admin.Top = 0;
            this.m_Box_Admin.VisibleDynamicsValue = true;
            this.m_Box_Admin.Width = 64;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.Enabled = false;
            this.m_Rectangle.EnabledDynamicsValue = false;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 64;
            this.m_Rectangle.IsBlinkEnabled = true;
            this.m_Rectangle.Left = 0;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "MainScreen";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.StrokeThickness = 0;
            this.m_Rectangle.Top = 0;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 64;
            // 
            // m_Button_Admin
            // 
            this.m_Button_Admin.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button_Admin.BlinkDynamicsValue = false;
            this.m_Button_Admin.DelayMouseInputPeriod = 0;
            this.m_Button_Admin.EnabledDynamicsValue = true;
            this.m_Button_Admin.FontSizePixels = 15;
            this.m_Button_Admin.ForceTransparency = true;
            this.m_Button_Admin.Height = 64;
            this.m_Button_Admin.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(14D, 14D, 14D, 14D);
            this.m_Button_Admin.IndicatorMargin = null;
            this.m_Button_Admin.Left = 0;
            this.m_Button_Admin.Name = "m_Button_Admin";
            this.m_Button_Admin.RequiresTransparency = true;
            this.m_Button_Admin.ScreenOwnerName = "MainScreen";
            this.m_Button_Admin.SymbolHeight = 32;
            this.m_Button_Admin.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button_Admin.SymbolName = "ic_administration";
            this.m_Button_Admin.SymbolWidth = 28;
            this.m_Button_Admin.TextHeight = 18;
            this.m_Button_Admin.TextMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF();
            this.m_Button_Admin.TextValue = 0D;
            this.m_Button_Admin.TextWidth = 60;
            this.m_Button_Admin.Top = 0;
            this.m_Button_Admin.Transparent = true;
            this.m_Button_Admin.Value = 0D;
            this.m_Button_Admin.VisibleDynamicsValue = true;
            this.m_Button_Admin.VisualPropertiesHashCode = 584783247;
            this.m_Button_Admin.Width = 64;
            this.m_Menu_Admin.Components.Add(this.m_Box_Admin);
            this.m_Menu_Admin.Components.Add(this.m_Rectangle);
            this.m_Menu_Admin.Components.Add(this.m_Button_Admin);
            this.m_Menu_Admin.DelayMouseInputPeriod = 0;
            this.m_Menu_Admin.EnabledDynamicsValue = true;
            this.m_Menu_Admin.Height = 64;
            this.m_Menu_Admin.Left = 0;
            this.m_Menu_Admin.Name = "m_Menu_Admin";
            this.m_Menu_Admin.ParentGroup = this.m_Bar_Menu;
            this.m_Menu_Admin.ScreenOwnerName = "MainScreen";
            this.m_Menu_Admin.Top = 128;
            this.m_Menu_Admin.VisibleDynamicsValue = true;
            this.m_Menu_Admin.Width = 64;
            this.m_Bar_Menu.Components.Add(this.m_MenuBar);
            this.m_Bar_Menu.Components.Add(this.m_Menu_Overview);
            this.m_Bar_Menu.Components.Add(this.m_Menu_Diagnostics);
            this.m_Bar_Menu.Components.Add(this.m_Menu_LogIn);
            this.m_Bar_Menu.Components.Add(this.m_Menu_Settings);
            this.m_Bar_Menu.Components.Add(this.m_Menu_Admin);
            this.m_Bar_Menu.DelayMouseInputPeriod = 0;
            this.m_Bar_Menu.EnabledDynamicsValue = true;
            this.m_Bar_Menu.Height = 416;
            this.m_Bar_Menu.Left = 0;
            this.m_Bar_Menu.Name = "m_Bar_Menu";
            this.m_Bar_Menu.ParentGroup = null;
            this.m_Bar_Menu.ScreenOwnerName = "MainScreen";
            this.m_Bar_Menu.Top = 64;
            this.m_Bar_Menu.VisibleDynamicsValue = true;
            this.m_Bar_Menu.Width = 64;
            this.m_Menu_Overview.ParentGroup = this.m_Bar_Menu;
            this.m_Menu_Overview.ScreenOwnerName = "MainScreen";
            this.m_Menu_Overview.Top = 0;
            this.m_Menu_Overview.VisibleDynamicsValue = true;
            this.m_Menu_Overview.Width = 64;
            // 
            // m_StatusBar
            // 
            this.m_StatusBar.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_StatusBar.BlinkDynamicsValue = false;
            this.m_StatusBar.DelayMouseInputPeriod = 0;
            this.m_StatusBar.Enabled = false;
            this.m_StatusBar.EnabledDynamicsValue = false;
            this.m_StatusBar.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(43)))), ((int)(((byte)(43))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_StatusBar.Height = 64;
            this.m_StatusBar.Left = 0;
            this.m_StatusBar.Name = "m_StatusBar";
            this.m_StatusBar.ScreenOwnerName = "MainScreen";
            this.m_StatusBar.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_StatusBar.StrokeThickness = 0;
            this.m_StatusBar.Top = 0;
            this.m_StatusBar.VisibleDynamicsValue = true;
            this.m_StatusBar.Width = 800;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "Segoe UI";
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.m_Text.Height = 21;
            this.m_Text.IsBlinkEnabled = true;
            this.m_Text.Left = 333;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text.ScreenOwnerName = "MainScreen";
            this.m_Text.Top = 17;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 69;
            // 
            // m_Time
            // 
            this.m_Time.BlinkDynamicsValue = false;
            this.m_Time.Bold = true;
            this.m_Time.DelayMouseInputPeriod = 0;
            this.m_Time.EnabledDynamicsValue = true;
            this.m_Time.FontFamily = "Segoe UI";
            this.m_Time.FontSizePixels = 18;
            this.m_Time.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Time.Height = 6;
            this.m_Time.Left = 592;
            this.m_Time.Name = "m_Time";
            this.m_Time.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Time.ScreenOwnerName = "MainScreen";
            this.m_Time.TextHorizontalAlignment = "Right";
            this.m_Time.TextVerticalAlignment = "Center";
            this.m_Time.Top = 17;
            this.m_Time.VisibleDynamicsValue = true;
            this.m_Time.Width = 2;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            messagelibrarydynamicsconvertercf1.MessageLibraryGroupName = "StatusBar_Status";
            messagelibrarydynamicsconvertercf1.MessageLibraryGroupResolver = messagelibrarygroupresolver1;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontFamily = "Segoe UI";
            this.m_Text1.FontSizePixels = 18;
            this.m_Text1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text1.Height = 6;
            this.m_Text1.Left = 16;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Text1.ScreenOwnerName = "MainScreen";
            this.m_Text1.Top = 0;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 2;
            // 
            // m_Ellipse
            // 
            this.m_Ellipse.BlinkDynamicsValue = false;
            brushdynamicsconvertercf4.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            brushcfinterval10.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval11.End = 1D;
            brushcfinterval11.Start = 1D;
            brushcfinterval11.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(19)))), ((int)(((byte)(183)))), ((int)(((byte)(32))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval12.End = 2D;
            brushcfinterval12.Start = 2D;
            brushcfinterval12.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval13.End = 3D;
            brushcfinterval13.Start = 3D;
            brushcfinterval13.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval10);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval11);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval12);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval13);
            this.m_Ellipse.DelayMouseInputPeriod = 0;
            this.m_Ellipse.Enabled = false;
            this.m_Ellipse.EnabledDynamicsValue = false;
            this.m_Ellipse.Fill = null;
            this.m_Ellipse.Height = 16;
            this.m_Ellipse.Left = 0;
            this.m_Ellipse.Name = "m_Ellipse";
            this.m_Ellipse.ScreenOwnerName = "MainScreen";
            this.m_Ellipse.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Ellipse.StrokeThickness = 0;
            this.m_Ellipse.Top = 8;
            this.m_Ellipse.VisibleDynamicsValue = true;
            this.m_Ellipse.Width = 16;
            // 
            // m_Status
            // 
            this.m_Status.BlinkDynamicsValue = false;
            this.m_Status.Components.Add(this.m_Text1);
            this.m_Status.Components.Add(this.m_Ellipse);
            this.m_Status.DelayMouseInputPeriod = 0;
            this.m_Status.EnabledDynamicsValue = true;
            this.m_Status.Height = 31;
            this.m_Status.Left = 16;
            this.m_Status.Name = "m_Status";
            // 
            // m_Bar_Status
            // 
            this.m_Bar_Status.BlinkDynamicsValue = false;
            // 
            // m_User
            // 
            this.m_User.BlinkDynamicsValue = false;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.Bold = true;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontFamily = "Segoe UI";
            this.m_Text2.FontSizePixels = 18;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 6;
            this.m_Text2.Left = 17;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.5D, 0D, 4.5D, 1D);
            this.m_Text2.ScreenOwnerName = "MainScreen";
            this.m_Text2.Top = 0;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 2;
            // 
            // m_Picture5
            // 
            this.m_Picture5.BlinkDynamicsValue = false;
            this.m_Picture5.DelayMouseInputPeriod = 0;
            this.m_Picture5.EnabledDynamicsValue = true;
            this.m_Picture5.Height = 18;
            this.m_Picture5.Left = 0;
            this.m_Picture5.Name = "m_Picture5";
            this.m_Picture5.ScreenOwnerName = "MainScreen";
            this.m_Picture5.SymbolName = "ic_profile";
            this.m_Picture5.Top = 8;
            this.m_Picture5.VisibleDynamicsValue = true;
            this.m_Picture5.Width = 18;
            this.m_User.Components.Add(this.m_Text2);
            this.m_User.Components.Add(this.m_Picture5);
            this.m_User.DelayMouseInputPeriod = 0;
            this.m_User.EnabledDynamicsValue = true;
            this.m_User.Height = 31;
            this.m_User.Left = 16;
            this.m_User.Name = "m_User";
            this.m_User.ParentGroup = this.m_Bar_Status;
            this.m_User.ScreenOwnerName = "MainScreen";
            this.m_User.Top = 3;
            this.m_User.VisibleDynamicsValue = true;
            this.m_User.Width = 108;
            this.m_Bar_Status.Components.Add(this.m_StatusBar);
            this.m_Bar_Status.Components.Add(this.m_Text);
            this.m_Bar_Status.Components.Add(this.m_Time);
            this.m_Bar_Status.Components.Add(this.m_Status);
            this.m_Bar_Status.Components.Add(this.m_User);
            this.m_Bar_Status.DelayMouseInputPeriod = 0;
            this.m_Bar_Status.EnabledDynamicsValue = true;
            this.m_Bar_Status.Height = 64;
            this.m_Bar_Status.Left = 0;
            this.m_Bar_Status.Name = "m_Bar_Status";
            this.m_Bar_Status.ParentGroup = null;
            this.m_Bar_Status.ScreenOwnerName = "MainScreen";
            this.m_Bar_Status.Top = -1;
            this.m_Bar_Status.VisibleDynamicsValue = true;
            this.m_Bar_Status.Width = 800;
            this.m_Status.ParentGroup = this.m_Bar_Status;
            this.m_Status.ScreenOwnerName = "MainScreen";
            this.m_Status.Top = 31;
            this.m_Status.VisibleDynamicsValue = true;
            this.m_Status.Width = 86;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "MainScreen";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_MainScreen = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
            this.SecurityGroups = SecurityGroups.Group_01 | SecurityGroups.Group_02;
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_Ellipse, SecurityGroups.Group_01 | SecurityGroups.Group_02);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_MainScreen) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_MenuBar);
            this.DrawingPrimitives.Add(this.m_Box_Overview);
            this.DrawingPrimitives.Add(this.m_Button_Overview);
            this.DrawingPrimitives.Add(this.m_Menu_Overview);
            this.DrawingPrimitives.Add(this.m_Box_Diagnostics);
            this.DrawingPrimitives.Add(this.m_Button_Diagnostics);
            this.DrawingPrimitives.Add(this.m_Menu_Diagnostics);
            this.DrawingPrimitives.Add(this.m_Box_LogIn);
            this.DrawingPrimitives.Add(this.m_Button_LogIn);
            this.DrawingPrimitives.Add(this.m_Menu_LogIn);
            this.DrawingPrimitives.Add(this.m_Box_Settings);
            this.DrawingPrimitives.Add(this.m_Button_Settings);
            this.DrawingPrimitives.Add(this.m_Menu_Settings);
            this.DrawingPrimitives.Add(this.m_Box_Admin);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Button_Admin);
            this.DrawingPrimitives.Add(this.m_Menu_Admin);
            this.DrawingPrimitives.Add(this.m_Bar_Menu);
            this.DrawingPrimitives.Add(this.m_StatusBar);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Time);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Ellipse);
            this.DrawingPrimitives.Add(this.m_Status);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Picture5);
            this.DrawingPrimitives.Add(this.m_User);
            this.DrawingPrimitives.Add(this.m_Bar_Status);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Overview)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Diagnostics)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Diagnostics)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_LogIn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_LogIn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Settings)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Settings)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button_Admin)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Admin)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Bar_Menu)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Menu_Overview)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Time)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_User)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Bar_Status)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Status)).EndInit();
        }
        
        private void m_Button_Overview_Action_Click(object sender, System.EventArgs e) {
            this.LogClose("m_Button_Overview", "Click", "Close Screen", "");
            this.Close();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button_Overview", "Click", "Show Screen", "OverviewScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.OverviewScreen.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button_Overview", "Click", "Set Analog", "Tags.HMI_Main_CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Main_CurrentScreen.SetAnalog(0);
        }
        
        private void m_Button_Diagnostics_Action_Click(object sender, System.EventArgs e) {
            this.LogClose("m_Button_Diagnostics", "Click", "Close Screen", "");
            this.Close();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button_Diagnostics", "Click", "Show Screen", "DiagnosticsScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.DiagnosticsScreen.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button_Diagnostics", "Click", "Set Analog", "Tags.HMI_Main_CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Main_CurrentScreen.SetAnalog(1);
        }
        
        private void m_Button_LogIn_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button_LogIn", "Click", "Login", "Security", "");
            Neo.ApplicationFramework.Generated.Globals.Security.Login();
        }
        
        private void m_Button_Settings_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button_Settings", "Click", "Show Backlight Settings", "", "");
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IBacklightService>().ShowBacklightSettings();
        }
        
        private void m_Button_Admin_Action_Click(object sender, System.EventArgs e) {
            this.LogClose("m_Button_Admin", "Click", "Close Screen", "");
            this.Close();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button_Admin", "Click", "Show Screen", "AdministrationScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.AdministrationScreen.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(MainScreen));
            this.m_Text.Text = resources.GetText("MainScreen.Text.Text", "EMERGENCY");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_MainScreen) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Fill", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Main_CurrentScreen"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Box_Overview.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Fill", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Main_CurrentScreen"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_Box_Diagnostics.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Fill", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Main_CurrentScreen"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf3);
            this.m_Box_Admin.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Main_Status"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 3));
            this.m_Rectangle.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Main_Status"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 3));
            this.m_Text.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Text", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagDateTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.RawConverterCF.Default);
            this.m_Time.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Text", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Main_Status"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, messagelibrarydynamicsconvertercf1);
            this.m_Text1.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Fill", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_Main_Status"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf4);
            this.m_Ellipse.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Text", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagCurrentUser"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.RawConverterCF.Default);
            this.m_Text2.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
        }
    }
}
