//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Tag1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag span;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Ymax;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Ymin;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Offset;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag TrendButtonsEnabled;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagScreenUpdateTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagCommunicationErrors;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagBacklightBrightnessLevel;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagAvailableRAM;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagPhysicalRAM;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagUsedRAM;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagAvailableStorage;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagStorageMemory;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagUsedStorage;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagDateTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagDayofWeek;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagProjectName;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagCPULoad;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagUsedRAMPercent;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagUsedStoragePercent;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem HMI_Main_Status;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Main_CurrentScreen;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagCurrentUser;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Fault_ErrorCode;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_FIL4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_FIL3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_FIL2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_FIL1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_FloorCall4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_CurrentFloor;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_FloorCall1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_FloorCall2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_FloorCall3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_ServiceTime1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_ServiceTime2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_ServiceTime3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_ServiceTime4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_Reset;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_Fault_Status_201;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_Fault_Status_202;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_Fault_Status_203;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_HPBE5;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_Fault_Status_1001;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_Fault_Status_1002;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_Fault_Status_1003;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_ResetFloor1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_ResetFloor2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_ResetFloor3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_ResetFloor4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_IL4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_IL3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_IL2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_IL1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_HPB4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_HPB3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_HPB2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_HPB1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_HPBO;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_HPBC;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_Elevator_DCLS;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_MaintenanceRequiredFloor1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_MaintenanceRequiredFloor2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_MaintenanceRequiredFloor3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag HMI_SharedData_MaintenanceRequiredFloor4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MaintenanceRequiredFloor1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MaintenanceRequiredFloor2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MaintenanceRequiredFloor3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MaintenanceRequiredFloor4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.HMI_Main_Status.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Main_Status_Action_ValueChange);
			this.HMI_Main_CurrentScreen.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Main_CurrentScreen_Action_ValueChange);
			this.HMI_Fault_ErrorCode.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Fault_ErrorCode_Action_ValueChange);
			this.HMI_Elevator_FIL4.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_FIL4_Action_ValueChange);
			this.HMI_Elevator_FIL3.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_FIL3_Action_ValueChange);
			this.HMI_Elevator_FIL2.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_FIL2_Action_ValueChange);
			this.HMI_Elevator_FIL1.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_FIL1_Action_ValueChange);
			this.HMI_SharedData_FloorCall4.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_FloorCall4_Action_ValueChange);
			this.HMI_Elevator_CurrentFloor.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_CurrentFloor_Action_ValueChange);
			this.HMI_SharedData_FloorCall1.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_FloorCall1_Action_ValueChange);
			this.HMI_SharedData_FloorCall2.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_FloorCall2_Action_ValueChange);
			this.HMI_SharedData_FloorCall3.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_FloorCall3_Action_ValueChange);
			this.HMI_SharedData_ServiceTime1.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_ServiceTime1_Action_ValueChange);
			this.HMI_SharedData_ServiceTime2.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_ServiceTime2_Action_ValueChange);
			this.HMI_SharedData_ServiceTime3.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_ServiceTime3_Action_ValueChange);
			this.HMI_SharedData_ServiceTime4.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_ServiceTime4_Action_ValueChange);
			this.HMI_Elevator_Reset.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_Reset_Action_ValueChange);
			this.HMI_SharedData_Fault_Status_201.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_Fault_Status_201_Action_ValueChange);
			this.HMI_SharedData_Fault_Status_202.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_Fault_Status_202_Action_ValueChange);
			this.HMI_SharedData_Fault_Status_203.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_Fault_Status_203_Action_ValueChange);
			this.HMI_Elevator_HPBE5.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_HPBE5_Action_ValueChange);
			this.HMI_SharedData_Fault_Status_1001.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_Fault_Status_1001_Action_ValueChange);
			this.HMI_SharedData_Fault_Status_1002.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_SharedData_Fault_Status_1002_Action_ValueChange);
			this.HMI_Elevator_HPB3.ValueChange += new System.EventHandler<Core.Api.DataSource.ValueChangedEventArgs>(this.HMI_Elevator_HPB3_Action_ValueChange);
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.Tag1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Tag1", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.span = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("span", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Ymax = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Ymax", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Ymin = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Ymin", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Offset = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Offset", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.TrendButtonsEnabled = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("TrendButtonsEnabled", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.SystemTagScreenUpdateTime = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Screen Update Time", "SystemTagScreenUpdateTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "The screen update time (in ms)", ((short)(1)), "", "");
			this.SystemTagCommunicationErrors = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Communication Errors", "SystemTagCommunicationErrors", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Number of active communication errors on all controllers", ((short)(1)), "", "");
			this.SystemTagBacklightBrightnessLevel = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Backlight Brightness Level", "SystemTagBacklightBrightnessLevel", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Backlight brightness level (in percent)", ((short)(1)), "", "");
			this.SystemTagAvailableRAM = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Available RAM", "SystemTagAvailableRAM", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Amount of RAM memory available (in kB)", ((short)(1)), "", "");
			this.SystemTagPhysicalRAM = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Physical RAM", "SystemTagPhysicalRAM", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "RAM memory installed in computer (in kB)", ((short)(1)), "", "");
			this.SystemTagUsedRAM = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Used RAM", "SystemTagUsedRAM", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Amount of RAM memory used (in kB)", ((short)(1)), "", "");
			this.SystemTagAvailableStorage = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Available Storage", "SystemTagAvailableStorage", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Amount of storage memory available (in MB)", ((short)(1)), "", "");
			this.SystemTagStorageMemory = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Storage Memory", "SystemTagStorageMemory", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Storage memory installed in computer (in MB)", ((short)(1)), "", "");
			this.SystemTagUsedStorage = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Used Storage", "SystemTagUsedStorage", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Amount of storage memory used (in MB)", ((short)(1)), "", "");
			this.SystemTagDateTime = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("DateTime", "SystemTagDateTime", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DATETIME)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Current date and time", ((short)(1)), "", "");
			this.SystemTagDayofWeek = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Day of Week", "SystemTagDayofWeek", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Day of current week", ((short)(1)), "", "");
			this.SystemTagProjectName = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Project Name", "SystemTagProjectName", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(100)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Name of the current project", ((short)(1)), "", "");
			this.SystemTagCPULoad = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("CPU Load", "SystemTagCPULoad", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Amount of CPU capacity used (in percent)", ((short)(1)), "", "");
			this.SystemTagUsedRAMPercent = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Used RAM Percent", "SystemTagUsedRAMPercent", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Amount of RAM memory used (in percent of physical)", ((short)(1)), "", "");
			this.SystemTagUsedStoragePercent = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Used Storage Percent", "SystemTagUsedStoragePercent", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Amount of storage memory used (in percent of all storage)", ((short)(1)), "", "");
			this.HMI_Main_Status = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("HMI_Main_Status", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.HMI_Main_CurrentScreen = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Main_CurrentScreen", "Controller1.DataItem2", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.SystemTagCurrentUser = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Current User", "SystemTagCurrentUser", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(100)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "The username of the currently logged in user", ((short)(1)), "", "");
			this.HMI_Fault_ErrorCode = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Fault_ErrorCode", "Controller1.DataItem3", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_Elevator_FIL4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_FIL4", "Controller1.DataItem6", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_Elevator_FIL3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_FIL3", "Controller1.DataItem7", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_Elevator_FIL2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_FIL2", "Controller1.DataItem8", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_Elevator_FIL1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_FIL1", "Controller1.DataItem9", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_SharedData_FloorCall4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_FloorCall4", "Controller1.DataItem10", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_Elevator_CurrentFloor = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_CurrentFloor", "Controller1.DataItem11", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_FloorCall1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_FloorCall1", "Controller1.DataItem12", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_FloorCall2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_FloorCall2", "Controller1.DataItem13", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_FloorCall3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_FloorCall3", "Controller1.DataItem14", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_ServiceTime1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_ServiceTime1", "Controller1.DataItem15", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_ServiceTime2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_ServiceTime2", "Controller1.DataItem16", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_ServiceTime3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_ServiceTime3", "Controller1.DataItem17", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_ServiceTime4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_ServiceTime4", "Controller1.DataItem18", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_Elevator_Reset = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_Reset", "Controller1.DataItem5", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_SharedData_Fault_Status_201 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_Fault_Status_201", "Controller1.DataItem20", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_SharedData_Fault_Status_202 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_Fault_Status_202", "Controller1.DataItem21", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_Fault_Status_203 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_Fault_Status_203", "Controller1.DataItem22", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_Elevator_HPBE5 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_HPBE5", "Controller1.DataItem4", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_SharedData_Fault_Status_1001 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_Fault_Status_1001", "Controller1.DataItem25", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_SharedData_Fault_Status_1002 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_Fault_Status_1002", "Controller1.DataItem26", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_SharedData_Fault_Status_1003 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_Fault_Status_1003", "Controller1.DataItem27", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.HMI_Elevator_ResetFloor1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_ResetFloor1", "Controller1.DataItem28", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_ResetFloor2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_ResetFloor2", "Controller1.DataItem29", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_ResetFloor3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_ResetFloor3", "Controller1.DataItem30", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_ResetFloor4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_ResetFloor4", "Controller1.DataItem31", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_IL4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_IL4", "Controller1.DataItem32", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_Elevator_IL3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_IL3", "Controller1.DataItem33", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_Elevator_IL2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_IL2", "Controller1.DataItem34", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_Elevator_IL1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_IL1", "Controller1.DataItem35", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_Elevator_HPB4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_HPB4", "Controller1.DataItem36", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_HPB3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_HPB3", "Controller1.DataItem37", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_HPB2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_HPB2", "Controller1.DataItem38", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_HPB1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_HPB1", "Controller1.DataItem39", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_HPBO = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_HPBO", "Controller1.DataItem40", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_HPBC = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_HPBC", "Controller1.DataItem41", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_Elevator_DCLS = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_Elevator_DCLS", "Controller1.DataItem19", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.HMI_SharedData_MaintenanceRequiredFloor1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_MaintenanceRequiredFloor1", "Controller1.DataItem23", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_SharedData_MaintenanceRequiredFloor2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_MaintenanceRequiredFloor2", "Controller1.DataItem24", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_SharedData_MaintenanceRequiredFloor3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_MaintenanceRequiredFloor3", "Controller1.DataItem42", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.HMI_SharedData_MaintenanceRequiredFloor4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("HMI_SharedData_MaintenanceRequiredFloor4", "Controller1.DataItem43", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.MaintenanceRequiredFloor1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MaintenanceRequiredFloor1", "Controller1.DataItem44", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MaintenanceRequiredFloor2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MaintenanceRequiredFloor2", "Controller1.DataItem45", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MaintenanceRequiredFloor3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MaintenanceRequiredFloor3", "Controller1.DataItem46", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.MaintenanceRequiredFloor4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MaintenanceRequiredFloor4", "Controller1.DataItem47", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.SystemTagScreenUpdateTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagCommunicationErrors.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagBacklightBrightnessLevel.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("100"), 0, new string[0], new string[0], true));
			this.SystemTagAvailableRAM.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagPhysicalRAM.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagUsedRAM.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagAvailableStorage.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagStorageMemory.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagUsedStorage.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagDateTime.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("4/29/2021 3:39:18 PM"), 0, new string[0], new string[0], true));
			this.SystemTagDayofWeek.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagProjectName.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("HMI"), 0, new string[0], new string[0], true));
			this.SystemTagCPULoad.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagUsedRAMPercent.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagUsedStoragePercent.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.HMI_Main_Status.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller1"}, new string[] {
							"DataItem1"}, true));
			this.SystemTagCurrentUser.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.LightweightTags.Add(this.Tag1);
			this.LightweightTags.Add(this.span);
			this.LightweightTags.Add(this.Ymax);
			this.LightweightTags.Add(this.Ymin);
			this.LightweightTags.Add(this.Offset);
			this.LightweightTags.Add(this.TrendButtonsEnabled);
			this.GlobalDataItems.Add(this.SystemTagScreenUpdateTime);
			this.GlobalDataItems.Add(this.SystemTagCommunicationErrors);
			this.GlobalDataItems.Add(this.SystemTagBacklightBrightnessLevel);
			this.GlobalDataItems.Add(this.SystemTagAvailableRAM);
			this.GlobalDataItems.Add(this.SystemTagPhysicalRAM);
			this.GlobalDataItems.Add(this.SystemTagUsedRAM);
			this.GlobalDataItems.Add(this.SystemTagAvailableStorage);
			this.GlobalDataItems.Add(this.SystemTagStorageMemory);
			this.GlobalDataItems.Add(this.SystemTagUsedStorage);
			this.GlobalDataItems.Add(this.SystemTagDateTime);
			this.GlobalDataItems.Add(this.SystemTagDayofWeek);
			this.GlobalDataItems.Add(this.SystemTagProjectName);
			this.GlobalDataItems.Add(this.SystemTagCPULoad);
			this.GlobalDataItems.Add(this.SystemTagUsedRAMPercent);
			this.GlobalDataItems.Add(this.SystemTagUsedStoragePercent);
			this.GlobalDataItems.Add(this.HMI_Main_Status);
			this.LightweightTags.Add(this.HMI_Main_CurrentScreen);
			this.GlobalDataItems.Add(this.SystemTagCurrentUser);
			this.LightweightTags.Add(this.HMI_Fault_ErrorCode);
			this.LightweightTags.Add(this.HMI_Elevator_FIL4);
			this.LightweightTags.Add(this.HMI_Elevator_FIL3);
			this.LightweightTags.Add(this.HMI_Elevator_FIL2);
			this.LightweightTags.Add(this.HMI_Elevator_FIL1);
			this.LightweightTags.Add(this.HMI_SharedData_FloorCall4);
			this.LightweightTags.Add(this.HMI_Elevator_CurrentFloor);
			this.LightweightTags.Add(this.HMI_SharedData_FloorCall1);
			this.LightweightTags.Add(this.HMI_SharedData_FloorCall2);
			this.LightweightTags.Add(this.HMI_SharedData_FloorCall3);
			this.LightweightTags.Add(this.HMI_SharedData_ServiceTime1);
			this.LightweightTags.Add(this.HMI_SharedData_ServiceTime2);
			this.LightweightTags.Add(this.HMI_SharedData_ServiceTime3);
			this.LightweightTags.Add(this.HMI_SharedData_ServiceTime4);
			this.LightweightTags.Add(this.HMI_Elevator_Reset);
			this.LightweightTags.Add(this.HMI_SharedData_Fault_Status_201);
			this.LightweightTags.Add(this.HMI_SharedData_Fault_Status_202);
			this.LightweightTags.Add(this.HMI_SharedData_Fault_Status_203);
			this.LightweightTags.Add(this.HMI_Elevator_HPBE5);
			this.LightweightTags.Add(this.HMI_SharedData_Fault_Status_1001);
			this.LightweightTags.Add(this.HMI_SharedData_Fault_Status_1002);
			this.LightweightTags.Add(this.HMI_SharedData_Fault_Status_1003);
			this.LightweightTags.Add(this.HMI_Elevator_ResetFloor1);
			this.LightweightTags.Add(this.HMI_Elevator_ResetFloor2);
			this.LightweightTags.Add(this.HMI_Elevator_ResetFloor3);
			this.LightweightTags.Add(this.HMI_Elevator_ResetFloor4);
			this.LightweightTags.Add(this.HMI_Elevator_IL4);
			this.LightweightTags.Add(this.HMI_Elevator_IL3);
			this.LightweightTags.Add(this.HMI_Elevator_IL2);
			this.LightweightTags.Add(this.HMI_Elevator_IL1);
			this.LightweightTags.Add(this.HMI_Elevator_HPB4);
			this.LightweightTags.Add(this.HMI_Elevator_HPB3);
			this.LightweightTags.Add(this.HMI_Elevator_HPB2);
			this.LightweightTags.Add(this.HMI_Elevator_HPB1);
			this.LightweightTags.Add(this.HMI_Elevator_HPBO);
			this.LightweightTags.Add(this.HMI_Elevator_HPBC);
			this.LightweightTags.Add(this.HMI_Elevator_DCLS);
			this.LightweightTags.Add(this.HMI_SharedData_MaintenanceRequiredFloor1);
			this.LightweightTags.Add(this.HMI_SharedData_MaintenanceRequiredFloor2);
			this.LightweightTags.Add(this.HMI_SharedData_MaintenanceRequiredFloor3);
			this.LightweightTags.Add(this.HMI_SharedData_MaintenanceRequiredFloor4);
			this.LightweightTags.Add(this.MaintenanceRequiredFloor1);
			this.LightweightTags.Add(this.MaintenanceRequiredFloor2);
			this.LightweightTags.Add(this.MaintenanceRequiredFloor3);
			this.LightweightTags.Add(this.MaintenanceRequiredFloor4);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		private void HMI_Main_Status_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Main_Status.Value == 1))
			{
			}
		}
		
		private void HMI_Main_CurrentScreen_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Main_CurrentScreen.Value == 1))
			{
			}
		}
		
		private void HMI_Fault_ErrorCode_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Fault_ErrorCode.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_FIL4_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_FIL4.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_FIL3_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_FIL3.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_FIL2_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_FIL2.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_FIL1_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_FIL1.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_FloorCall4_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_FloorCall4.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_CurrentFloor_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_CurrentFloor.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_FloorCall1_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_FloorCall1.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_FloorCall2_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_FloorCall2.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_FloorCall3_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_FloorCall3.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_ServiceTime1_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_ServiceTime1.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_ServiceTime2_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_ServiceTime2.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_ServiceTime3_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_ServiceTime3.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_ServiceTime4_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_ServiceTime4.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_Reset_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_Reset.Value == ((bool)(System.Convert.ChangeType(1, typeof(bool), System.Globalization.CultureInfo.CurrentCulture)))))
			{
			}
		}
		
		private void HMI_SharedData_Fault_Status_201_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_Fault_Status_201.Value == ((bool)(System.Convert.ChangeType(1, typeof(bool), System.Globalization.CultureInfo.CurrentCulture)))))
			{
			}
		}
		
		private void HMI_SharedData_Fault_Status_202_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_Fault_Status_202.Value == 1))
			{
			}
		}
		
		private void HMI_SharedData_Fault_Status_203_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_Fault_Status_203.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_HPBE5_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_HPBE5.Value == ((bool)(System.Convert.ChangeType(1, typeof(bool), System.Globalization.CultureInfo.CurrentCulture)))))
			{
			}
		}
		
		private void HMI_SharedData_Fault_Status_1001_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_Fault_Status_1001.Value == ((bool)(System.Convert.ChangeType(1, typeof(bool), System.Globalization.CultureInfo.CurrentCulture)))))
			{
			}
		}
		
		private void HMI_SharedData_Fault_Status_1002_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_SharedData_Fault_Status_1002.Value == 1))
			{
			}
		}
		
		private void HMI_Elevator_HPB3_Action_ValueChange(object sender, System.EventArgs e)
		{
			if ((Neo.ApplicationFramework.Generated.Globals.Tags.HMI_Elevator_HPB3.Value == ((bool)(System.Convert.ChangeType(1, typeof(bool), System.Globalization.CultureInfo.CurrentCulture)))))
			{
			}
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
