//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class TrendAdvanced_X2pro7 : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.ComboBox m_ComboBox1;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolControl1;
        
        private Neo.ApplicationFramework.Controls.Trend.TrendViewerCF m_Trend1;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolControl4;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolControl2;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolControl3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnBack100Percent;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnBack25Percent;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPause;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPlay;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnForward25Percent;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnForward100Percent;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnZoomIn;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnZoomOut;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPanUp;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPanDown;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnRestore;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnLegend;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnLastSample;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock3;
        
        private Neo.ApplicationFramework.Controls.Controls.DigitalClockCF m_DigitalClock4;
        
        private Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF m_SymbolControl5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture1;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group1;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private bool m_Initialized_TrendAdvanced_X2pro7;
        
        private Neo.ApplicationFramework.Common.Dynamics.TimeSpanSecondsConverterCF timespansecondsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.TimeSpanSecondsConverterCF timespansecondsconvertercf2;
        
        public TrendAdvanced_X2pro7() {
            this.InitializeComponent();
            this.btnBack100Percent.Click += new System.EventHandler(this.btnBack100Percent_Click);
            this.btnBack25Percent.Click += new System.EventHandler(this.btnBack25Percent_Click);
            this.btnPause.Click += new System.EventHandler(this.btnPause_Click);
            this.btnPlay.Click += new System.EventHandler(this.btnPlay_Click);
            this.btnForward25Percent.Click += new System.EventHandler(this.btnForward25Percent_Click);
            this.btnForward100Percent.Click += new System.EventHandler(this.btnForward100Percent_Click);
            this.btnZoomIn.Click += new System.EventHandler(this.btnZoomIn_Click);
            this.btnZoomOut.Click += new System.EventHandler(this.btnZoomOut_Click);
            this.btnPanUp.Click += new System.EventHandler(this.btnPanUp_Click);
            this.btnPanDown.Click += new System.EventHandler(this.btnPanDown_Click);
            this.btnRestore.Click += new System.EventHandler(this.btnRestore_Click);
            this.btnLegend.Click += new System.EventHandler(this.btnLegend_Click);
            this.btnLastSample.Click += new System.EventHandler(this.btnLastSample_Click);
            this.Adapter.Closed += new System.EventHandler(this.Other_Trend_Closed);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolControl1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolControl1);
            }
        }
        
        public Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase Trend1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TrendCFAdapterBase>(this.m_Trend1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolControl4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolControl4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolControl2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolControl2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolControl3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolControl3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnBack100Percent {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnBack100Percent);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnBack25Percent {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnBack25Percent);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPause {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPause);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPlay {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPlay);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnForward25Percent {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnForward25Percent);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnForward100Percent {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnForward100Percent);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnZoomIn {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnZoomIn);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnZoomOut {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnZoomOut);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPanUp {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPanUp);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPanDown {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPanDown);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnRestore {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnRestore);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnLegend {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnLegend);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnLastSample {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnLastSample);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter ComboBox1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter>(this.m_ComboBox1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter DigitalClock4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_DigitalClock4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SymbolControl5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SymbolControl5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        private void InitializeComponent() {
            this.timespansecondsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.TimeSpanSecondsConverterCF();
            this.timespansecondsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.TimeSpanSecondsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf5 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper13 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_ComboBox1 = new Neo.ApplicationFramework.Controls.Controls.ComboBox();
            this.m_SymbolControl1 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_Trend1 = new Neo.ApplicationFramework.Controls.Trend.TrendViewerCF();
            this.m_SymbolControl4 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolControl2 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_SymbolControl3 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_btnBack100Percent = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnBack25Percent = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPause = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPlay = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnForward25Percent = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnForward100Percent = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnZoomIn = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnZoomOut = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPanUp = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPanDown = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnRestore = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnLegend = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnLastSample = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_DigitalClock3 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_DigitalClock4 = new Neo.ApplicationFramework.Controls.Controls.DigitalClockCF();
            this.m_SymbolControl5 = new Neo.ApplicationFramework.Controls.Controls.SymbolViewboxCF();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture4 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture1 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Group1 = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_ComboBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Trend1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnBack100Percent)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnBack25Percent)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPause)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPlay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnForward25Percent)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnForward100Percent)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnZoomIn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnZoomOut)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPanUp)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPanDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnRestore)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnLegend)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnLastSample)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            this.SuspendLayout();
            // 
            // TrendAdvanced_X2pro7
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_ComboBox1
            // 
            this.m_ComboBox1.EnabledDynamicsValue = true;
            this.m_ComboBox1.FontFamily = "Tahoma";
            this.m_ComboBox1.FontSizePixels = 14;
            this.m_ComboBox1.ForeColor = System.Drawing.Color.Black;
            stringintervalmappercf1.DefaultValue = null;
            stringintervalcf1.End = 30D;
            stringintervalcf1.Start = 30D;
            stringintervalcf1.Value = "30 seconds";
            stringintervalcf2.End = 60D;
            stringintervalcf2.Start = 60D;
            stringintervalcf2.Value = "1 minute";
            stringintervalcf3.End = 240D;
            stringintervalcf3.Start = 240D;
            stringintervalcf3.Value = "4 minutes";
            stringintervalcf4.End = 600D;
            stringintervalcf4.Start = 600D;
            stringintervalcf4.Value = "10 minutes";
            stringintervalcf5.End = 1800D;
            stringintervalcf5.Start = 1800D;
            stringintervalcf5.Value = "30 minutes";
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            stringintervalmappercf1.Intervals.Add(stringintervalcf3);
            stringintervalmappercf1.Intervals.Add(stringintervalcf4);
            stringintervalmappercf1.Intervals.Add(stringintervalcf5);
            this.m_ComboBox1.IntervalMapper = stringintervalmappercf1;
            this.m_ComboBox1.Location = new System.Drawing.Point(362, 430);
            this.m_ComboBox1.Name = "m_ComboBox1";
            this.m_ComboBox1.Size = new System.Drawing.Size(113, 21);
            this.m_ComboBox1.TabIndex = 2147483647;
            this.m_ComboBox1.VisibleDynamicsValue = true;
            // 
            // m_SymbolControl1
            // 
            this.m_SymbolControl1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(216)))), ((int)(((byte)(216))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolControl1.BlinkDynamicsValue = false;
            this.m_SymbolControl1.DelayMouseInputPeriod = 0;
            this.m_SymbolControl1.EnabledDynamicsValue = true;
            this.m_SymbolControl1.ForceTransparency = false;
            this.m_SymbolControl1.Height = 421;
            this.m_SymbolControl1.IndicatorMargin = null;
            this.m_SymbolControl1.Left = 11;
            this.m_SymbolControl1.Name = "m_SymbolControl1";
            this.m_SymbolControl1.RequiresTransparency = false;
            this.m_SymbolControl1.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_SymbolControl1.Top = 45;
            this.m_SymbolControl1.Value = 0D;
            this.m_SymbolControl1.VisibleDynamicsValue = true;
            this.m_SymbolControl1.Width = 775;
            // 
            // m_Trend1
            // 
            this.m_Trend1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Trend1.BlinkDynamicsValue = false;
            this.m_Trend1.DelayMouseInputPeriod = 0;
            this.m_Trend1.EnabledDynamicsValue = true;
            this.m_Trend1.FontSizePixels = 16;
            this.m_Trend1.ForceTransparency = false;
            this.m_Trend1.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Trend1.GridLineColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Trend1.Height = 302;
            this.m_Trend1.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(51.2D, 15D, 50.889999999999986D, 39.313333333333333D);
            this.m_Trend1.Left = 43;
            this.m_Trend1.Name = "m_Trend1";
            this.m_Trend1.RequiresTransparency = true;
            this.m_Trend1.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Trend1.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Trend1.TimeOffset = System.TimeSpan.Parse("00:00:00");
            this.m_Trend1.TimeRange = System.TimeSpan.Parse("00:04:00");
            this.m_Trend1.TimeScaleMaximum = 39083.5D;
            this.m_Trend1.TimeScaleMinimum = 39083.49722222222D;
            this.m_Trend1.TimeTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(51.2D, 274.68666666666667D, 51.199999999999932D, 8D);
            this.m_Trend1.Top = 58;
            this.m_Trend1.Value = 0D;
            this.m_Trend1.ValueMajorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(38.2D, 15D, 588.8D, 39.313333333333333D);
            this.m_Trend1.ValueMajorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(588.80000000000007D, 15D, 38.199999999999932D, 39.313333333333333D);
            this.m_Trend1.ValueMinorScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(42.2D, 15D, 588.8D, 39.313333333333333D);
            this.m_Trend1.ValueMinorScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(588.80000000000007D, 15D, 42.199999999999932D, 39.313333333333333D);
            this.m_Trend1.ValueScaleMajorTickCount = 6;
            this.m_Trend1.ValueScaleMaximum = 0D;
            this.m_Trend1.ValueScaleMinimum = 0D;
            this.m_Trend1.ValueScaleMinorTickCount = 1;
            this.m_Trend1.ValueTextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(10D, 15D, 598.8D, 39.313333333333333D);
            this.m_Trend1.ValueTextScaleMaxMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(598.80000000000007D, 15D, 9.9999999999998863D, 39.313333333333333D);
            this.m_Trend1.VisibleDynamicsValue = true;
            this.m_Trend1.Width = 635;
            // 
            // m_SymbolControl4
            // 
            this.m_SymbolControl4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolControl4.BlinkDynamicsValue = false;
            this.m_SymbolControl4.DelayMouseInputPeriod = 0;
            this.m_SymbolControl4.EnabledDynamicsValue = true;
            this.m_SymbolControl4.ForceTransparency = false;
            this.m_SymbolControl4.Height = 44;
            this.m_SymbolControl4.IndicatorMargin = null;
            this.m_SymbolControl4.Left = 233;
            this.m_SymbolControl4.Name = "m_SymbolControl4";
            this.m_SymbolControl4.RequiresTransparency = true;
            this.m_SymbolControl4.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_SymbolControl4.Top = 416;
            this.m_SymbolControl4.Value = 0D;
            this.m_SymbolControl4.VisibleDynamicsValue = true;
            this.m_SymbolControl4.Width = 256;
            // 
            // m_SymbolControl2
            // 
            this.m_SymbolControl2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolControl2.BlinkDynamicsValue = false;
            this.m_SymbolControl2.DelayMouseInputPeriod = 0;
            this.m_SymbolControl2.EnabledDynamicsValue = true;
            this.m_SymbolControl2.ForceTransparency = false;
            this.m_SymbolControl2.Height = 320;
            this.m_SymbolControl2.IndicatorMargin = null;
            this.m_SymbolControl2.Left = 695;
            this.m_SymbolControl2.Name = "m_SymbolControl2";
            this.m_SymbolControl2.RequiresTransparency = true;
            this.m_SymbolControl2.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_SymbolControl2.Top = 60;
            this.m_SymbolControl2.Value = 0D;
            this.m_SymbolControl2.VisibleDynamicsValue = true;
            this.m_SymbolControl2.Width = 69;
            // 
            // m_SymbolControl3
            // 
            this.m_SymbolControl3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolControl3.BlinkDynamicsValue = false;
            this.m_SymbolControl3.DelayMouseInputPeriod = 0;
            this.m_SymbolControl3.EnabledDynamicsValue = true;
            this.m_SymbolControl3.ForceTransparency = false;
            this.m_SymbolControl3.Height = 59;
            this.m_SymbolControl3.IndicatorMargin = null;
            this.m_SymbolControl3.Left = 92;
            this.m_SymbolControl3.Name = "m_SymbolControl3";
            this.m_SymbolControl3.RequiresTransparency = true;
            this.m_SymbolControl3.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_SymbolControl3.Top = 368;
            this.m_SymbolControl3.Value = 0D;
            this.m_SymbolControl3.VisibleDynamicsValue = true;
            this.m_SymbolControl3.Width = 552;
            // 
            // m_btnBack100Percent
            // 
            this.m_btnBack100Percent.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnBack100Percent.BlinkDynamicsValue = false;
            this.m_btnBack100Percent.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnBack100Percent.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnBack100Percent.DelayMouseInputPeriod = 0;
            this.m_btnBack100Percent.EnabledDynamicsValue = true;
            this.m_btnBack100Percent.FontSizePixels = 10;
            this.m_btnBack100Percent.ForceTransparency = true;
            this.m_btnBack100Percent.Height = 46;
            this.m_btnBack100Percent.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 3D);
            this.m_btnBack100Percent.ImageStretch = true;
            this.m_btnBack100Percent.IndicatorMargin = null;
            this.m_btnBack100Percent.Left = 102;
            this.m_btnBack100Percent.Name = "m_btnBack100Percent";
            this.m_btnBack100Percent.RequiresTransparency = true;
            this.m_btnBack100Percent.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnBack100Percent.StyleName = "Chrome";
            this.m_btnBack100Percent.SymbolHeight = 38;
            this.m_btnBack100Percent.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_btnBack100Percent.SymbolName = "backward";
            this.m_btnBack100Percent.SymbolWidth = 38;
            this.m_btnBack100Percent.TextHeight = 12;
            this.m_btnBack100Percent.TextValue = 0D;
            this.m_btnBack100Percent.TextWidth = 68;
            this.m_btnBack100Percent.Top = 375;
            this.m_btnBack100Percent.Value = 0D;
            this.m_btnBack100Percent.VisibleDynamicsValue = true;
            this.m_btnBack100Percent.VisualPropertiesHashCode = 86582469;
            this.m_btnBack100Percent.Width = 74;
            // 
            // m_btnBack25Percent
            // 
            this.m_btnBack25Percent.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnBack25Percent.BlinkDynamicsValue = false;
            this.m_btnBack25Percent.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnBack25Percent.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnBack25Percent.DelayMouseInputPeriod = 0;
            this.m_btnBack25Percent.EnabledDynamicsValue = true;
            this.m_btnBack25Percent.FontSizePixels = 10;
            this.m_btnBack25Percent.ForceTransparency = true;
            this.m_btnBack25Percent.Height = 46;
            this.m_btnBack25Percent.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 3D);
            this.m_btnBack25Percent.ImageStretch = true;
            this.m_btnBack25Percent.IndicatorMargin = null;
            this.m_btnBack25Percent.Left = 178;
            this.m_btnBack25Percent.Name = "m_btnBack25Percent";
            this.m_btnBack25Percent.RequiresTransparency = true;
            this.m_btnBack25Percent.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnBack25Percent.StyleName = "Chrome";
            this.m_btnBack25Percent.SymbolHeight = 38;
            this.m_btnBack25Percent.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_btnBack25Percent.SymbolName = "previous (1)";
            this.m_btnBack25Percent.SymbolWidth = 38;
            this.m_btnBack25Percent.TextHeight = 12;
            this.m_btnBack25Percent.TextValue = 0D;
            this.m_btnBack25Percent.TextWidth = 68;
            this.m_btnBack25Percent.Top = 375;
            this.m_btnBack25Percent.Value = 0D;
            this.m_btnBack25Percent.VisibleDynamicsValue = true;
            this.m_btnBack25Percent.VisualPropertiesHashCode = 525861521;
            this.m_btnBack25Percent.Width = 74;
            // 
            // m_btnPause
            // 
            this.m_btnPause.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnPause.BlinkDynamicsValue = false;
            this.m_btnPause.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPause.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnPause.DelayMouseInputPeriod = 0;
            this.m_btnPause.EnabledDynamicsValue = true;
            this.m_btnPause.FontSizePixels = 10;
            this.m_btnPause.ForceTransparency = true;
            this.m_btnPause.Height = 46;
            this.m_btnPause.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 3D);
            this.m_btnPause.ImageStretch = true;
            this.m_btnPause.IndicatorMargin = null;
            this.m_btnPause.Left = 254;
            this.m_btnPause.Name = "m_btnPause";
            this.m_btnPause.RequiresTransparency = true;
            this.m_btnPause.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnPause.StyleName = "Chrome";
            this.m_btnPause.SymbolHeight = 38;
            this.m_btnPause.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_btnPause.SymbolName = "pause";
            this.m_btnPause.SymbolWidth = 38;
            this.m_btnPause.TextHeight = 12;
            this.m_btnPause.TextValue = 0D;
            this.m_btnPause.TextWidth = 68;
            this.m_btnPause.Top = 375;
            this.m_btnPause.Value = 0D;
            this.m_btnPause.VisibleDynamicsValue = true;
            this.m_btnPause.VisualPropertiesHashCode = -1975960664;
            this.m_btnPause.Width = 74;
            // 
            // m_btnPlay
            // 
            this.m_btnPlay.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnPlay.BlinkDynamicsValue = false;
            this.m_btnPlay.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPlay.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnPlay.DelayMouseInputPeriod = 0;
            this.m_btnPlay.EnabledDynamicsValue = true;
            this.m_btnPlay.FontSizePixels = 10;
            this.m_btnPlay.ForceTransparency = true;
            this.m_btnPlay.Height = 46;
            this.m_btnPlay.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 3D);
            this.m_btnPlay.ImageStretch = true;
            this.m_btnPlay.IndicatorMargin = null;
            this.m_btnPlay.Left = 330;
            this.m_btnPlay.Name = "m_btnPlay";
            this.m_btnPlay.RequiresTransparency = true;
            this.m_btnPlay.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnPlay.StyleName = "Chrome";
            this.m_btnPlay.SymbolHeight = 38;
            this.m_btnPlay.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_btnPlay.SymbolName = "play";
            this.m_btnPlay.SymbolWidth = 38;
            this.m_btnPlay.TextHeight = 12;
            this.m_btnPlay.TextValue = 0D;
            this.m_btnPlay.TextWidth = 68;
            this.m_btnPlay.Top = 375;
            this.m_btnPlay.Value = 0D;
            this.m_btnPlay.VisibleDynamicsValue = true;
            this.m_btnPlay.VisualPropertiesHashCode = 137257594;
            this.m_btnPlay.Width = 74;
            // 
            // m_btnForward25Percent
            // 
            this.m_btnForward25Percent.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnForward25Percent.BlinkDynamicsValue = false;
            this.m_btnForward25Percent.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnForward25Percent.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnForward25Percent.DelayMouseInputPeriod = 0;
            this.m_btnForward25Percent.EnabledDynamicsValue = true;
            this.m_btnForward25Percent.FontSizePixels = 10;
            this.m_btnForward25Percent.ForceTransparency = true;
            this.m_btnForward25Percent.Height = 46;
            this.m_btnForward25Percent.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 3D);
            this.m_btnForward25Percent.ImageStretch = true;
            this.m_btnForward25Percent.IndicatorMargin = null;
            this.m_btnForward25Percent.Left = 406;
            this.m_btnForward25Percent.Name = "m_btnForward25Percent";
            this.m_btnForward25Percent.RequiresTransparency = true;
            this.m_btnForward25Percent.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnForward25Percent.StyleName = "Chrome";
            this.m_btnForward25Percent.SymbolHeight = 38;
            this.m_btnForward25Percent.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_btnForward25Percent.SymbolName = "next (1)";
            this.m_btnForward25Percent.SymbolWidth = 38;
            this.m_btnForward25Percent.TextHeight = 12;
            this.m_btnForward25Percent.TextValue = 0D;
            this.m_btnForward25Percent.TextWidth = 68;
            this.m_btnForward25Percent.Top = 375;
            this.m_btnForward25Percent.Value = 0D;
            this.m_btnForward25Percent.VisibleDynamicsValue = true;
            this.m_btnForward25Percent.VisualPropertiesHashCode = 514206270;
            this.m_btnForward25Percent.Width = 74;
            // 
            // m_btnForward100Percent
            // 
            this.m_btnForward100Percent.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnForward100Percent.BlinkDynamicsValue = false;
            this.m_btnForward100Percent.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnForward100Percent.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnForward100Percent.DelayMouseInputPeriod = 0;
            this.m_btnForward100Percent.EnabledDynamicsValue = true;
            this.m_btnForward100Percent.FontSizePixels = 10;
            this.m_btnForward100Percent.ForceTransparency = true;
            this.m_btnForward100Percent.Height = 46;
            this.m_btnForward100Percent.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 3D);
            this.m_btnForward100Percent.ImageStretch = true;
            this.m_btnForward100Percent.IndicatorMargin = null;
            this.m_btnForward100Percent.Left = 482;
            this.m_btnForward100Percent.Name = "m_btnForward100Percent";
            this.m_btnForward100Percent.RequiresTransparency = true;
            this.m_btnForward100Percent.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnForward100Percent.StyleName = "Chrome";
            this.m_btnForward100Percent.SymbolHeight = 38;
            this.m_btnForward100Percent.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_btnForward100Percent.SymbolName = "forward";
            this.m_btnForward100Percent.SymbolWidth = 38;
            this.m_btnForward100Percent.TextHeight = 12;
            this.m_btnForward100Percent.TextValue = 0D;
            this.m_btnForward100Percent.TextWidth = 68;
            this.m_btnForward100Percent.Top = 375;
            this.m_btnForward100Percent.Value = 0D;
            this.m_btnForward100Percent.VisibleDynamicsValue = true;
            this.m_btnForward100Percent.VisualPropertiesHashCode = 94160226;
            this.m_btnForward100Percent.Width = 74;
            // 
            // m_btnZoomIn
            // 
            this.m_btnZoomIn.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnZoomIn.BlinkDynamicsValue = false;
            this.m_btnZoomIn.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnZoomIn.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnZoomIn.DelayMouseInputPeriod = 0;
            this.m_btnZoomIn.EnabledDynamicsValue = true;
            this.m_btnZoomIn.FontSizePixels = 10;
            this.m_btnZoomIn.ForceTransparency = true;
            this.m_btnZoomIn.Height = 49;
            this.m_btnZoomIn.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 7D, 2D, 7D);
            this.m_btnZoomIn.ImageStretch = true;
            this.m_btnZoomIn.IndicatorMargin = null;
            this.m_btnZoomIn.Left = 700;
            this.m_btnZoomIn.Name = "m_btnZoomIn";
            this.m_btnZoomIn.RequiresTransparency = true;
            this.m_btnZoomIn.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnZoomIn.StyleName = "Chrome";
            this.m_btnZoomIn.SymbolHeight = 33;
            this.m_btnZoomIn.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_btnZoomIn.SymbolName = "zoom in";
            this.m_btnZoomIn.SymbolWidth = 33;
            this.m_btnZoomIn.TextHeight = 12;
            this.m_btnZoomIn.TextValue = 0D;
            this.m_btnZoomIn.TextWidth = 54;
            this.m_btnZoomIn.Top = 64;
            this.m_btnZoomIn.Value = 0D;
            this.m_btnZoomIn.VisibleDynamicsValue = true;
            this.m_btnZoomIn.VisualPropertiesHashCode = -1028852912;
            this.m_btnZoomIn.Width = 60;
            // 
            // m_btnZoomOut
            // 
            this.m_btnZoomOut.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnZoomOut.BlinkDynamicsValue = false;
            this.m_btnZoomOut.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnZoomOut.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnZoomOut.DelayMouseInputPeriod = 0;
            this.m_btnZoomOut.EnabledDynamicsValue = true;
            this.m_btnZoomOut.FontSizePixels = 10;
            this.m_btnZoomOut.ForceTransparency = true;
            this.m_btnZoomOut.Height = 49;
            this.m_btnZoomOut.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 7D, 2D, 7D);
            this.m_btnZoomOut.ImageStretch = true;
            this.m_btnZoomOut.IndicatorMargin = null;
            this.m_btnZoomOut.Left = 700;
            this.m_btnZoomOut.Name = "m_btnZoomOut";
            this.m_btnZoomOut.RequiresTransparency = true;
            this.m_btnZoomOut.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnZoomOut.StyleName = "Chrome";
            this.m_btnZoomOut.SymbolHeight = 33;
            this.m_btnZoomOut.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_btnZoomOut.SymbolName = "zoom out";
            this.m_btnZoomOut.SymbolWidth = 33;
            this.m_btnZoomOut.TextHeight = 12;
            this.m_btnZoomOut.TextValue = 0D;
            this.m_btnZoomOut.TextWidth = 54;
            this.m_btnZoomOut.Top = 116;
            this.m_btnZoomOut.Value = 0D;
            this.m_btnZoomOut.VisibleDynamicsValue = true;
            this.m_btnZoomOut.VisualPropertiesHashCode = 651411283;
            this.m_btnZoomOut.Width = 60;
            // 
            // m_btnPanUp
            // 
            this.m_btnPanUp.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnPanUp.BlinkDynamicsValue = false;
            this.m_btnPanUp.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPanUp.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnPanUp.DelayMouseInputPeriod = 0;
            this.m_btnPanUp.EnabledDynamicsValue = true;
            this.m_btnPanUp.FontSizePixels = 10;
            this.m_btnPanUp.ForceTransparency = true;
            this.m_btnPanUp.Height = 49;
            this.m_btnPanUp.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 7D, 2D, 7D);
            this.m_btnPanUp.ImageStretch = true;
            this.m_btnPanUp.IndicatorMargin = null;
            this.m_btnPanUp.Left = 700;
            this.m_btnPanUp.Name = "m_btnPanUp";
            this.m_btnPanUp.RequiresTransparency = true;
            this.m_btnPanUp.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnPanUp.StyleName = "Chrome";
            this.m_btnPanUp.SymbolHeight = 33;
            this.m_btnPanUp.SymbolIntervalMapper = symbolintervalmapper9;
            this.m_btnPanUp.SymbolName = "panup";
            this.m_btnPanUp.SymbolWidth = 33;
            this.m_btnPanUp.TextHeight = 12;
            this.m_btnPanUp.TextValue = 0D;
            this.m_btnPanUp.TextWidth = 54;
            this.m_btnPanUp.Top = 168;
            this.m_btnPanUp.Value = 0D;
            this.m_btnPanUp.VisibleDynamicsValue = true;
            this.m_btnPanUp.VisualPropertiesHashCode = 1294190288;
            this.m_btnPanUp.Width = 60;
            // 
            // m_btnPanDown
            // 
            this.m_btnPanDown.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnPanDown.BlinkDynamicsValue = false;
            this.m_btnPanDown.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPanDown.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnPanDown.DelayMouseInputPeriod = 0;
            this.m_btnPanDown.EnabledDynamicsValue = true;
            this.m_btnPanDown.FontSizePixels = 10;
            this.m_btnPanDown.ForceTransparency = true;
            this.m_btnPanDown.Height = 49;
            this.m_btnPanDown.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 7D, 2D, 7D);
            this.m_btnPanDown.ImageStretch = true;
            this.m_btnPanDown.IndicatorMargin = null;
            this.m_btnPanDown.Left = 700;
            this.m_btnPanDown.Name = "m_btnPanDown";
            this.m_btnPanDown.RequiresTransparency = true;
            this.m_btnPanDown.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnPanDown.StyleName = "Chrome";
            this.m_btnPanDown.SymbolHeight = 33;
            this.m_btnPanDown.SymbolIntervalMapper = symbolintervalmapper10;
            this.m_btnPanDown.SymbolName = "pandown";
            this.m_btnPanDown.SymbolWidth = 33;
            this.m_btnPanDown.TextHeight = 12;
            this.m_btnPanDown.TextValue = 0D;
            this.m_btnPanDown.TextWidth = 54;
            this.m_btnPanDown.Top = 220;
            this.m_btnPanDown.Value = 0D;
            this.m_btnPanDown.VisibleDynamicsValue = true;
            this.m_btnPanDown.VisualPropertiesHashCode = 1553695384;
            this.m_btnPanDown.Width = 60;
            // 
            // m_btnRestore
            // 
            this.m_btnRestore.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnRestore.BlinkDynamicsValue = false;
            this.m_btnRestore.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnRestore.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnRestore.DelayMouseInputPeriod = 0;
            this.m_btnRestore.EnabledDynamicsValue = true;
            this.m_btnRestore.FontSizePixels = 10;
            this.m_btnRestore.ForceTransparency = true;
            this.m_btnRestore.Height = 49;
            this.m_btnRestore.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 7D, 2D, 7D);
            this.m_btnRestore.ImageStretch = true;
            this.m_btnRestore.IndicatorMargin = null;
            this.m_btnRestore.Left = 700;
            this.m_btnRestore.Name = "m_btnRestore";
            this.m_btnRestore.RequiresTransparency = true;
            this.m_btnRestore.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnRestore.StyleName = "Chrome";
            this.m_btnRestore.SymbolHeight = 33;
            this.m_btnRestore.SymbolIntervalMapper = symbolintervalmapper11;
            this.m_btnRestore.SymbolName = "close (1)";
            this.m_btnRestore.SymbolWidth = 33;
            this.m_btnRestore.TextHeight = 12;
            this.m_btnRestore.TextValue = 0D;
            this.m_btnRestore.TextWidth = 54;
            this.m_btnRestore.Top = 272;
            this.m_btnRestore.Value = 0D;
            this.m_btnRestore.VisibleDynamicsValue = true;
            this.m_btnRestore.VisualPropertiesHashCode = -374982172;
            this.m_btnRestore.Width = 60;
            // 
            // m_btnLegend
            // 
            this.m_btnLegend.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnLegend.BlinkDynamicsValue = false;
            this.m_btnLegend.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnLegend.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnLegend.DelayMouseInputPeriod = 0;
            this.m_btnLegend.EnabledDynamicsValue = true;
            this.m_btnLegend.FontSizePixels = 10;
            this.m_btnLegend.ForceTransparency = true;
            this.m_btnLegend.Height = 49;
            this.m_btnLegend.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 7D, 2D, 7D);
            this.m_btnLegend.ImageStretch = true;
            this.m_btnLegend.IndicatorMargin = null;
            this.m_btnLegend.Left = 700;
            this.m_btnLegend.Name = "m_btnLegend";
            this.m_btnLegend.RequiresTransparency = true;
            this.m_btnLegend.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnLegend.StyleName = "Chrome";
            this.m_btnLegend.SymbolHeight = 33;
            this.m_btnLegend.SymbolIntervalMapper = symbolintervalmapper12;
            this.m_btnLegend.SymbolName = "trend";
            this.m_btnLegend.SymbolWidth = 33;
            this.m_btnLegend.TextHeight = 12;
            this.m_btnLegend.TextValue = 0D;
            this.m_btnLegend.TextWidth = 54;
            this.m_btnLegend.Top = 325;
            this.m_btnLegend.Value = 0D;
            this.m_btnLegend.VisibleDynamicsValue = true;
            this.m_btnLegend.VisualPropertiesHashCode = -1173232001;
            this.m_btnLegend.Width = 60;
            // 
            // m_btnLastSample
            // 
            this.m_btnLastSample.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnLastSample.BlinkDynamicsValue = false;
            this.m_btnLastSample.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnLastSample.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_btnLastSample.DelayMouseInputPeriod = 0;
            this.m_btnLastSample.EnabledDynamicsValue = true;
            this.m_btnLastSample.FontSizePixels = 10;
            this.m_btnLastSample.ForceTransparency = true;
            this.m_btnLastSample.Height = 46;
            this.m_btnLastSample.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 3D);
            this.m_btnLastSample.ImageStretch = true;
            this.m_btnLastSample.IndicatorMargin = null;
            this.m_btnLastSample.Left = 558;
            this.m_btnLastSample.Name = "m_btnLastSample";
            this.m_btnLastSample.RequiresTransparency = true;
            this.m_btnLastSample.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_btnLastSample.StyleName = "Chrome";
            this.m_btnLastSample.SymbolHeight = 38;
            this.m_btnLastSample.SymbolIntervalMapper = symbolintervalmapper13;
            this.m_btnLastSample.SymbolName = "last";
            this.m_btnLastSample.SymbolWidth = 38;
            this.m_btnLastSample.TextHeight = 12;
            this.m_btnLastSample.TextValue = 0D;
            this.m_btnLastSample.TextWidth = 68;
            this.m_btnLastSample.Top = 375;
            this.m_btnLastSample.Value = 0D;
            this.m_btnLastSample.VisibleDynamicsValue = true;
            this.m_btnLastSample.VisualPropertiesHashCode = -838022562;
            this.m_btnLastSample.Width = 74;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 14;
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 241;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3.5D, 0D, 3.5D, 1D);
            this.m_Text1.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Text1.Top = 430;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 97;
            // 
            // m_DigitalClock3
            // 
            this.m_DigitalClock3.BlinkDynamicsValue = false;
            this.m_DigitalClock3.DelayMouseInputPeriod = 0;
            this.m_DigitalClock3.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Date;
            this.m_DigitalClock3.EnabledDynamicsValue = true;
            this.m_DigitalClock3.FontSizePixels = 14;
            this.m_DigitalClock3.Height = 19;
            this.m_DigitalClock3.Left = 18;
            this.m_DigitalClock3.Name = "m_DigitalClock3";
            this.m_DigitalClock3.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_DigitalClock3.ShowDayOfWeek = false;
            this.m_DigitalClock3.ShowSeconds = true;
            this.m_DigitalClock3.Text = "4/29/2021";
            this.m_DigitalClock3.Top = 5;
            this.m_DigitalClock3.VisibleDynamicsValue = true;
            this.m_DigitalClock3.Width = 86;
            // 
            // m_DigitalClock4
            // 
            this.m_DigitalClock4.BlinkDynamicsValue = false;
            this.m_DigitalClock4.DelayMouseInputPeriod = 0;
            this.m_DigitalClock4.DisplayFormat = Neo.ApplicationFramework.Interfaces.DateTimeDisplayFormat.Time;
            this.m_DigitalClock4.EnabledDynamicsValue = true;
            this.m_DigitalClock4.FontSizePixels = 14;
            this.m_DigitalClock4.Height = 19;
            this.m_DigitalClock4.Left = 20;
            this.m_DigitalClock4.Name = "m_DigitalClock4";
            this.m_DigitalClock4.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_DigitalClock4.ShowDayOfWeek = false;
            this.m_DigitalClock4.ShowSeconds = true;
            this.m_DigitalClock4.Text = "3:51:48 PM";
            this.m_DigitalClock4.Top = 20;
            this.m_DigitalClock4.VisibleDynamicsValue = true;
            this.m_DigitalClock4.Width = 93;
            // 
            // m_SymbolControl5
            // 
            this.m_SymbolControl5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_SymbolControl5.BlinkDynamicsValue = false;
            this.m_SymbolControl5.DelayMouseInputPeriod = 0;
            this.m_SymbolControl5.EnabledDynamicsValue = true;
            this.m_SymbolControl5.ForceTransparency = false;
            this.m_SymbolControl5.Height = 37;
            this.m_SymbolControl5.IndicatorMargin = null;
            this.m_SymbolControl5.Left = 255;
            this.m_SymbolControl5.Name = "m_SymbolControl5";
            this.m_SymbolControl5.RequiresTransparency = false;
            this.m_SymbolControl5.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_SymbolControl5.Top = 5;
            this.m_SymbolControl5.Value = 0D;
            this.m_SymbolControl5.VisibleDynamicsValue = true;
            this.m_SymbolControl5.Width = 290;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 16;
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 306;
            this.m_Text3.MultiLine = true;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text3.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Text3.Top = 11;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 154;
            // 
            // m_Picture4
            // 
            this.m_Picture4.BlinkDynamicsValue = false;
            this.m_Picture4.DelayMouseInputPeriod = 0;
            this.m_Picture4.EnabledDynamicsValue = true;
            this.m_Picture4.Height = 30;
            this.m_Picture4.Left = 273;
            this.m_Picture4.Name = "m_Picture4";
            this.m_Picture4.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Picture4.Stretch = true;
            this.m_Picture4.SymbolName = "warning";
            this.m_Picture4.Top = 7;
            this.m_Picture4.VisibleDynamicsValue = true;
            this.m_Picture4.Width = 30;
            // 
            // m_Text2
            // 
            this.m_Text2.AutoSize = false;
            this.m_Text2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3D, 3D, 3D, 3D);
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 16;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 177;
            this.m_Text2.Left = 0;
            this.m_Text2.MultiLine = true;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text2.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Text2.Top = 0;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 536;
            this.m_Text2.WordWrap = true;
            // 
            // m_Picture1
            // 
            this.m_Picture1.BlinkDynamicsValue = false;
            this.m_Picture1.DelayMouseInputPeriod = 0;
            this.m_Picture1.EnabledDynamicsValue = true;
            this.m_Picture1.Height = 87;
            this.m_Picture1.Left = 7;
            this.m_Picture1.Name = "m_Picture1";
            this.m_Picture1.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Picture1.Stretch = true;
            this.m_Picture1.SymbolName = "tags";
            this.m_Picture1.Top = 72;
            this.m_Picture1.VisibleDynamicsValue = true;
            this.m_Picture1.Width = 522;
            // 
            // m_Group1
            // 
            this.m_Group1.BlinkDynamicsValue = false;
            this.m_Group1.Components.Add(this.m_Text2);
            this.m_Group1.Components.Add(this.m_Picture1);
            this.m_Group1.DelayMouseInputPeriod = 0;
            this.m_Group1.EnabledDynamicsValue = true;
            this.m_Group1.Height = 177;
            this.m_Group1.Left = 92;
            this.m_Group1.Name = "m_Group1";
            this.m_Group1.ParentGroup = null;
            this.m_Group1.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Group1.Top = 124;
            this.m_Group1.VisibleDynamicsValue = true;
            this.m_Group1.Width = 536;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 29;
            this.m_Picture.Left = 702;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "TrendAdvanced_X2pro7";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "beijer-electronics1";
            this.m_Picture.Top = 7;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 72;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "TrendAdvanced_X2pro7";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "Other_Trend";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_TrendAdvanced_X2pro7 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_TrendAdvanced_X2pro7) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            this.Controls.Add(this.m_ComboBox1);
            ((System.ComponentModel.ISupportInitialize)(this.m_ComboBox1)).EndInit();
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_SymbolControl1);
            this.DrawingPrimitives.Add(this.m_Trend1);
            this.DrawingPrimitives.Add(this.m_SymbolControl4);
            this.DrawingPrimitives.Add(this.m_SymbolControl2);
            this.DrawingPrimitives.Add(this.m_SymbolControl3);
            this.DrawingPrimitives.Add(this.m_btnBack100Percent);
            this.DrawingPrimitives.Add(this.m_btnBack25Percent);
            this.DrawingPrimitives.Add(this.m_btnPause);
            this.DrawingPrimitives.Add(this.m_btnPlay);
            this.DrawingPrimitives.Add(this.m_btnForward25Percent);
            this.DrawingPrimitives.Add(this.m_btnForward100Percent);
            this.DrawingPrimitives.Add(this.m_btnZoomIn);
            this.DrawingPrimitives.Add(this.m_btnZoomOut);
            this.DrawingPrimitives.Add(this.m_btnPanUp);
            this.DrawingPrimitives.Add(this.m_btnPanDown);
            this.DrawingPrimitives.Add(this.m_btnRestore);
            this.DrawingPrimitives.Add(this.m_btnLegend);
            this.DrawingPrimitives.Add(this.m_btnLastSample);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_DigitalClock3);
            this.DrawingPrimitives.Add(this.m_DigitalClock4);
            this.DrawingPrimitives.Add(this.m_SymbolControl5);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Picture4);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Picture1);
            this.DrawingPrimitives.Add(this.m_Group1);
            this.DrawingPrimitives.Add(this.m_Picture);
            ((System.ComponentModel.ISupportInitialize)(this.m_Trend1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnBack100Percent)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnBack25Percent)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPause)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPlay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnForward25Percent)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnForward100Percent)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnZoomIn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnZoomOut)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPanUp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPanDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnRestore)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnLegend)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnLastSample)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_DigitalClock4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(TrendAdvanced_X2pro7));
            this.m_Text1.Text = resources.GetText("TrendAdvanced_X2pro7.Text1.Text", "Select time range:");
            this.m_Text3.Text = resources.GetText("TrendAdvanced_X2pro7.Text3.Text", "This template contains scripts");
            this.m_Text2.Text = resources.GetText("TrendAdvanced_X2pro7.Text2.Text", "Information (remove this text when finished reading it):\r\nDo not forget to assign" +
                    " initial values to Ymax, Ymin and span (on the Tags configuration page).");
            this.m_btnZoomIn.Text = resources.GetText("TrendAdvanced_X2pro7.btnZoomIn.Text", null);
            this.m_btnZoomOut.Text = resources.GetText("TrendAdvanced_X2pro7.btnZoomOut.Text", null);
            this.m_btnPanUp.Text = resources.GetText("TrendAdvanced_X2pro7.btnPanUp.Text", null);
            this.m_btnPanDown.Text = resources.GetText("TrendAdvanced_X2pro7.btnPanDown.Text", null);
            this.m_btnRestore.Text = resources.GetText("TrendAdvanced_X2pro7.btnRestore.Text", null);
            this.m_btnLegend.Text = resources.GetText("TrendAdvanced_X2pro7.btnLegend.Text", null);
            this.m_btnLastSample.Text = resources.GetText("TrendAdvanced_X2pro7.btnLastSample.Text", null);
            this.m_btnForward100Percent.Text = resources.GetText("TrendAdvanced_X2pro7.btnForward100Percent.Text", null);
            this.m_btnForward25Percent.Text = resources.GetText("TrendAdvanced_X2pro7.btnForward25Percent.Text", null);
            this.m_btnPlay.Text = resources.GetText("TrendAdvanced_X2pro7.btnPlay.Text", null);
            this.m_btnPause.Text = resources.GetText("TrendAdvanced_X2pro7.btnPause.Text", null);
            this.m_btnBack25Percent.Text = resources.GetText("TrendAdvanced_X2pro7.btnBack25Percent.Text", null);
            this.m_btnBack100Percent.Text = resources.GetText("TrendAdvanced_X2pro7.btnBack100Percent.Text", null);
            resources.ApplyTexts(this.m_ComboBox1, "Texts", "TrendAdvanced_X2pro7.ComboBox1.Texts[0]", "30 seconds", "TrendAdvanced_X2pro7.ComboBox1.Texts[1]", "1 minute", "TrendAdvanced_X2pro7.ComboBox1.Texts[2]", "4 minutes", "TrendAdvanced_X2pro7.ComboBox1.Texts[3]", "10 minutes", "TrendAdvanced_X2pro7.ComboBox1.Texts[4]", "30 minutes");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_TrendAdvanced_X2pro7) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.span"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_ComboBox1.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("ValueScaleMaximum", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Ymax"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.RawConverterCF.Default);
            this.m_Trend1.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("ValueScaleMinimum", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Ymin"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.RawConverterCF.Default);
            this.m_Trend1.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TimeRange", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.span"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, timespansecondsconvertercf1);
            this.m_Trend1.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TimeOffset", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Offset"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, timespansecondsconvertercf2);
            this.m_Trend1.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TrendButtonsEnabled"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_btnBack100Percent.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TrendButtonsEnabled"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_btnBack25Percent.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TrendButtonsEnabled"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_btnForward25Percent.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TrendButtonsEnabled"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_btnForward100Percent.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TrendButtonsEnabled"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_btnLastSample.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
        }
    }
}
